Repository rchain/rchain, pull requests merged in 2020-09, with the labels that each got.

#3121 RCHAIN-3952 - fix for LMDB read operation
  rspace/src/main/scala/coop/rchain/rspace/history/Store.scala
  rspace/src/main/scala/coop/rchain/rspace/history/StoreFactory.scala
  shared/src/main/scala/coop/rchain/lmdb/LMDBStore.scala
Labels: bug-fix

#3120 Make Justification regression work with LFS
  casper/src/main/scala/coop/rchain/casper/Validate.scala
  casper/src/test/scala/coop/rchain/casper/batch2/ValidateTest.scala
Labels: bug-fix

#3123 Refactor dagstore insert, allow reverse order adding
  block-storage/src/main/scala/coop/rchain/blockstorage/ByteStringKVStoreSyntax.scala
  block-storage/src/main/scala/coop/rchain/blockstorage/dag/BlockDagKeyValueStorage.scala
  block-storage/src/main/scala/coop/rchain/blockstorage/dag/BlockMetadataStore.scala
  block-storage/src/main/scala/coop/rchain/blockstorage/package.scala
Labels: bug-fix, enhancement

#3111 Fix requesting blocks and state chunks
  block-storage/src/main/scala/coop/rchain/blockstorage/dag/BlockDagKeyValueStorage.scala
  casper/src/main/scala/coop/rchain/casper/Casper.scala
  casper/src/main/scala/coop/rchain/casper/MultiParentCasperImpl.scala
  casper/src/main/scala/coop/rchain/casper/engine/Initializing.scala
  casper/src/main/scala/coop/rchain/casper/engine/LastFinalizedStateBlockRequester.scala
  casper/src/main/scala/coop/rchain/casper/engine/LastFinalizedStateTupleSpaceRequester.scala
  casper/src/test/scala/coop/rchain/casper/api/CreateBlockAPITest.scala
  casper/src/test/scala/coop/rchain/casper/engine/InitializingSpec.scala
  comm/src/main/scala/coop/rchain/comm/transport/TransportLayerSyntax.scala
  models/src/main/scala/coop/rchain/casper/PrettyPrinter.scala
Labels: bug-fix, enhancement

#3136 fix data inconsistent bug in tests
  casper/src/test/scala/coop/rchain/casper/engine/InitializingSpec.scala
  comm/src/test/scala/coop/rchain/p2p/EffectsTestInstances.scala
Labels: bug-fix

#3135 Send request for block message to single peer
  casper/src/main/scala/coop/rchain/casper/engine/Initializing.scala
  casper/src/main/scala/coop/rchain/casper/util/comm/CommUtil.scala
  comm/src/main/scala/coop/rchain/comm/rp/Connect.scala
Labels: enhancement

#3124 Enable per peer incoming message queues
  comm/src/main/scala/coop/rchain/comm/PeerNode.scala
  comm/src/main/scala/coop/rchain/comm/transport/GrpcTransportReceiver.scala
  comm/src/main/scala/coop/rchain/comm/transport/GrpcTransportServer.scala
  integration-tests/resources/logback.xml
  integration-tests/run_tests
  integration-tests/test/rnode.py
Labels: enhancement

#3140 swagger / openAPI document for rnode web API
  docs/rnode-api/Makefile
  docs/rnode-api/README.md
  docs/rnode-api/rnode-openapi-schema.ts
  docs/rnode-api/rnode-openapi.json
Labels: documentation
