Repository rchain/rchain, pull requests merged in 2020-10, with the labels that each got.

#3161 Disable oom test
  rholang/src/test/scala/coop/rchain/rholang/StackSafetySpec.scala
Labels: build-tests-ci

#3159 Internalise enqueued blocks set into Casper trait
  casper/src/main/scala/coop/rchain/casper/Casper.scala
  casper/src/main/scala/coop/rchain/casper/MultiParentCasperImpl.scala
  casper/src/main/scala/coop/rchain/casper/engine/BlockRetriever.scala
  casper/src/main/scala/coop/rchain/casper/engine/Running.scala
  casper/src/test/scala/coop/rchain/casper/api/CreateBlockAPITest.scala
  casper/src/test/scala/coop/rchain/casper/engine/RunningHandleBlockMessageSpec.scala
  casper/src/test/scala/coop/rchain/casper/helper/NoOpsCasperEffect.scala
  casper/src/test/scala/coop/rchain/casper/helper/TestNode.scala
Labels: bug-fix, enhancement

#3171 Upgrade to Monix3.2.2 and catsEffect2.2.0
  casper/src/main/scala/coop/rchain/casper/ReportingCasper.scala
  casper/src/main/scala/coop/rchain/casper/util/rholang/RuntimeManager.scala
  casper/src/test/scala/coop/rchain/casper/helper/BlockDagStorageFixture.scala
  comm/src/main/scala/coop/rchain/comm/transport/GrpcTransportClient.scala
  comm/src/test/scala/coop/rchain/comm/transport/TcpTransportLayerSpec.scala
  comm/src/test/scala/coop/rchain/comm/transport/TransportLayerRuntime.scala
  project/Dependencies.scala
  rspace/src/test/scala/coop/rchain/rspace/concurrent/TwoStepLockTest.scala
  shared/src/main/scala/coop/rchain/shared/Cell.scala
Labels: dependencies

#3179 Do not fetch blocks in processing
  casper/src/main/scala/coop/rchain/casper/MultiParentCasperImpl.scala
Labels: bug-fix

#3182 update plugins.sbt for sbt-jmh to 0.4.0 from 0.3.7
  project/plugins.sbt
Labels: dependencies

#3183 Update Dependencies.scala for scodec-bits to 1.1.20 from 1.1.18
  project/Dependencies.scala
Labels: dependencies
