Repository rchain/rchain, pull requests merged in 2020-08, with the labels that each got.

#2913 RCHAIN-4054: Last finalized state
  build.sbt
  casper/src/main/scala/coop/rchain/casper/engine/CasperLaunch.scala
  casper/src/main/scala/coop/rchain/casper/engine/Engine.scala
  casper/src/main/scala/coop/rchain/casper/engine/GenesisCeremonyMaster.scala
  casper/src/main/scala/coop/rchain/casper/engine/GenesisValidator.scala
  casper/src/main/scala/coop/rchain/casper/engine/Initializing.scala
  casper/src/main/scala/coop/rchain/casper/engine/LastFinalizedState.scala
  casper/src/main/scala/coop/rchain/casper/engine/LastFinalizedStateBlockRequester.scala
  casper/src/main/scala/coop/rchain/casper/engine/LastFinalizedStateTupleSpaceRequester.scala
  casper/src/main/scala/coop/rchain/casper/engine/Running.scala
  casper/src/main/scala/coop/rchain/casper/protocol/CasperMessageProtocol.scala
  casper/src/main/scala/coop/rchain/casper/protocol/package.scala
  casper/src/main/scala/coop/rchain/casper/state/BlockStateManager.scala
  casper/src/main/scala/coop/rchain/casper/state/RNodeStateManager.scala
  casper/src/main/scala/coop/rchain/casper/state/instances/BlockStateManagerImpl.scala
  casper/src/main/scala/coop/rchain/casper/util/ProtoUtil.scala
  casper/src/main/scala/coop/rchain/casper/util/comm/CommUtil.scala
  casper/src/test/scala/coop/rchain/casper/engine/GenesisCeremonyMasterSpec.scala
  casper/src/test/scala/coop/rchain/casper/engine/GenesisValidatorSpec.scala
  casper/src/test/scala/coop/rchain/casper/engine/InitializingSpec.scala
  casper/src/test/scala/coop/rchain/casper/engine/RunningSpec.scala
  casper/src/test/scala/coop/rchain/casper/helper/TestNode.scala
  models/src/main/protobuf/CasperMessage.proto
  models/src/main/scala/coop/rchain/casper/protocol/CasperMessage.scala
  models/src/main/scala/coop/rchain/casper/protocol/PacketTypeTag.scala
  node/src/main/scala/coop/rchain/node/NodeRuntime.scala
  node/src/main/scala/coop/rchain/node/api/AdminWebApi.scala
  node/src/main/scala/coop/rchain/node/api/WebApi.scala
  node/src/main/scala/coop/rchain/node/api/WebApiSyntax.scala
  node/src/main/scala/coop/rchain/node/state/instances/RNodeStateManagerImpl.scala
  node/src/main/scala/coop/rchain/node/web/AdminWebApiRoutes.scala
  node/src/test/scala/coop/rchain/state/TrieExporterSpec.scala
  project/Dependencies.scala
  rspace/src/main/scala/coop/rchain/rspace/Blake2b256Hash.scala
  rspace/src/main/scala/coop/rchain/rspace/history/History.scala
  rspace/src/main/scala/coop/rchain/rspace/history/HistoryRepository.scala
  rspace/src/main/scala/coop/rchain/rspace/history/HistoryRepositoryImpl.scala
  rspace/src/main/scala/coop/rchain/rspace/history/RootRepository.scala
  rspace/src/main/scala/coop/rchain/rspace/history/RootsStore.scala
  rspace/src/main/scala/coop/rchain/rspace/history/Store.scala
  rspace/src/main/scala/coop/rchain/rspace/history/StoreFactory.scala
  rspace/src/main/scala/coop/rchain/rspace/state/RSpaceExporter.scala
  rspace/src/main/scala/coop/rchain/rspace/state/RSpaceImporter.scala
  rspace/src/main/scala/coop/rchain/rspace/state/RSpaceStateManager.scala
  rspace/src/main/scala/coop/rchain/rspace/state/exporters/RSpaceExporterDisk.scala
  rspace/src/main/scala/coop/rchain/rspace/state/exporters/RSpaceExporterItems.scala
  rspace/src/main/scala/coop/rchain/rspace/state/instances/RSpaceExporterImpl.scala
  rspace/src/main/scala/coop/rchain/rspace/state/instances/RSpaceImporterImpl.scala
  rspace/src/main/scala/coop/rchain/rspace/state/instances/RSpaceStateManagerImpl.scala
  rspace/src/main/scala/coop/rchain/rspace/state/syntax/package.scala
  rspace/src/main/scala/coop/rchain/rspace/util/Lib.scala
  rspace/src/test/scala/coop/rchain/rspace/history/HistoryRepositoryGenerativeSpec.scala
  rspace/src/test/scala/coop/rchain/rspace/history/HistoryRepositorySpec.scala
  shared/src/main/scala/coop/rchain/lmdb/LMDBStore.scala
  shared/src/main/scala/coop/rchain/state/StateManager.scala
  shared/src/main/scala/coop/rchain/state/TrieExporter.scala
  shared/src/main/scala/coop/rchain/state/TrieImporter.scala
Labels: enhancement, feature-branch

#3065 Fix to prevent deploys with keys used for blessed (standard) contracts
  casper/src/main/scala/coop/rchain/casper/api/BlockAPI.scala
  casper/src/main/scala/coop/rchain/casper/genesis/contracts/StandardDeploys.scala
  casper/src/test/scala/coop/rchain/casper/genesis/contracts/StandardDeploysSpec.scala
Labels: bug-fix

#3068 Fix default use of post-state hash for exploratory deploy
  node/src/main/scala/coop/rchain/node/web/WebApiRoutes.scala
Labels: bug-fix

#3067 Do not traverse the whole DAG on unseenBlock
  casper/src/main/scala/coop/rchain/casper/util/ProtoUtil.scala
Labels: bug-fix

#3069 Use only active validators for sync constraint
  casper/src/main/scala/coop/rchain/casper/SynchronyConstraintChecker.scala
Labels: bug-fix

#3071 Fix timeout on HTTP server and HTTP propose response
  node/src/main/scala/coop/rchain/node/NodeRuntime.scala
  node/src/main/scala/coop/rchain/node/api/AdminWebApi.scala
  node/src/main/scala/coop/rchain/node/api/WebApi.scala
  node/src/main/scala/coop/rchain/node/api/WebApiSyntax.scala
  node/src/main/scala/coop/rchain/node/web/AdminWebApiRoutes.scala
  node/src/main/scala/coop/rchain/node/web/package.scala
Labels: bug-fix

#3070 Add BlockIsInProcessing ignore reason
  casper/src/main/scala/coop/rchain/casper/Casper.scala
  casper/src/main/scala/coop/rchain/casper/MultiParentCasperImpl.scala
  casper/src/main/scala/coop/rchain/casper/engine/BlockRetriever.scala
  casper/src/main/scala/coop/rchain/casper/engine/Running.scala
  casper/src/test/scala/coop/rchain/casper/api/CreateBlockAPITest.scala
  casper/src/test/scala/coop/rchain/casper/helper/NoOpsCasperEffect.scala
  casper/src/test/scala/coop/rchain/casper/helper/TestNode.scala
Labels: bug-fix, enhancement

#3073 Reorder ignore reason
  casper/src/main/scala/coop/rchain/casper/engine/Running.scala
Labels: bug-fix

#3099 Use Vector in trie traversal
  casper/src/main/scala/coop/rchain/casper/engine/Initializing.scala
  casper/src/main/scala/coop/rchain/casper/engine/LastFinalizedStateTupleSpaceRequester.scala
  casper/src/main/scala/coop/rchain/casper/engine/Running.scala
  casper/src/main/scala/coop/rchain/casper/util/comm/CommUtil.scala
  integration-tests/test/test_genesis_ceremony.py
  models/src/main/scala/coop/rchain/casper/protocol/CasperMessage.scala
  rspace/src/main/scala/coop/rchain/rspace/state/RSpaceExporter.scala
  rspace/src/main/scala/coop/rchain/rspace/state/exporters/RSpaceExporterDisk.scala
  rspace/src/main/scala/coop/rchain/rspace/state/exporters/RSpaceExporterItems.scala
  rspace/src/main/scala/coop/rchain/rspace/state/syntax/package.scala
  rspace/src/main/scala/coop/rchain/rspace/util/Lib.scala
Labels: enhancement

#3101 Remove debug logging in state requester
  casper/src/main/scala/coop/rchain/casper/engine/Initializing.scala
  casper/src/main/scala/coop/rchain/casper/engine/LastFinalizedStateTupleSpaceRequester.scala
Labels: diagnostics

#3106 Validate block even if it is in blockstore
  casper/src/main/scala/coop/rchain/casper/engine/Running.scala
Labels: bug-fix

#3107 Do not ask for dependencies for approved block child
  casper/src/main/scala/coop/rchain/casper/MultiParentCasperImpl.scala
  casper/src/main/scala/coop/rchain/casper/engine/Initializing.scala
Labels: bug-fix
