Repository rchain/rchain, pull requests merged in 2020-12, with the labels that each got.

#3254 Fix tests for LFS block requester
  build.sbt
  casper/src/main/scala/coop/rchain/casper/engine/Initializing.scala
  casper/src/main/scala/coop/rchain/casper/engine/LfsBlockRequester.scala
  casper/src/main/scala/coop/rchain/casper/engine/LfsTupleSpaceRequester.scala
  casper/src/test/scala/coop/rchain/casper/engine/InitializingSpec.scala
  casper/src/test/scala/coop/rchain/casper/engine/LfsBlockRequesterEffectsSpec.scala
  casper/src/test/scala/coop/rchain/casper/engine/LfsBlockRequesterStateSpec.scala
  node/src/main/resources/logback.xml
  shared/src/main/scala/coop/rchain/fs2/Fs2StreamSyntax.scala
  shared/src/main/scala/coop/rchain/shared/package.scala
Labels: build-tests-ci

#3251 Set finalized as true for valid old blocks (temp solution)
  casper/src/main/scala/coop/rchain/casper/api/BlockAPI.scala
Labels: enhancement

#3263 Finalized block bugs
  block-storage/src/main/scala/coop/rchain/blockstorage/dag/BlockMetadataStore.scala
  casper/src/main/scala/coop/rchain/casper/BlockCreator.scala
  casper/src/main/scala/coop/rchain/casper/EquivocationDetector.scala
  casper/src/main/scala/coop/rchain/casper/Estimator.scala
  casper/src/main/scala/coop/rchain/casper/SafetyOracle.scala
  casper/src/main/scala/coop/rchain/casper/Validate.scala
  casper/src/main/scala/coop/rchain/casper/api/BlockAPI.scala
  casper/src/main/scala/coop/rchain/casper/util/DagOperations.scala
  casper/src/main/scala/coop/rchain/casper/util/ProtoUtil.scala
  casper/src/test/scala/coop/rchain/casper/util/DagOperationsTest.scala
  shared/src/main/scala/coop/rchain/shared/DagOps.scala
Labels: bug-fix

#3267 Add conversion of Set in WebAPI, additional types as Map keys
  node/src/main/scala/coop/rchain/node/api/WebApi.scala
Labels: enhancement

#3265 LFS tuple space tests
  casper/src/main/scala/coop/rchain/casper/engine/Initializing.scala
  casper/src/main/scala/coop/rchain/casper/engine/LfsBlockRequester.scala
  casper/src/main/scala/coop/rchain/casper/engine/LfsTupleSpaceRequester.scala
  casper/src/test/scala/coop/rchain/casper/engine/LfsBlockRequesterEffectsSpec.scala
  casper/src/test/scala/coop/rchain/casper/engine/LfsBlockRequesterStateSpec.scala
  casper/src/test/scala/coop/rchain/casper/engine/LfsStateRequesterEffectsSpec.scala
  casper/src/test/scala/coop/rchain/casper/engine/LfsStateRequesterStateSpec.scala
  rspace/src/main/scala/coop/rchain/rspace/state/RSpaceImporter.scala
  shared/src/main/scala/coop/rchain/fs2/Fs2StreamSyntax.scala
Labels: build-tests-ci, feature-branch

#3269 Fix synchrony constraint calculation when latest block is older than approved
  casper/src/main/scala/coop/rchain/casper/SynchronyConstraintChecker.scala
  casper/src/main/scala/coop/rchain/casper/engine/CasperLaunch.scala
  casper/src/main/scala/coop/rchain/casper/engine/Running.scala
  casper/src/test/scala/coop/rchain/casper/api/CreateBlockAPITest.scala
  casper/src/test/scala/coop/rchain/casper/engine/Setup.scala
  casper/src/test/scala/coop/rchain/casper/helper/TestNode.scala
  integration-tests/resources/logback.xml
  node/src/main/scala/coop/rchain/node/NodeRuntime.scala
Labels: bug-fix, feature-branch

#3273 Fix for HTTP idle timeout, header timeout must be less than idle
  node/src/main/scala/coop/rchain/node/web/package.scala
Labels: bug-fix

#3272 Fix for state exporter flag to be able to disable export
  casper/src/main/scala/coop/rchain/casper/engine/CasperLaunch.scala
  casper/src/main/scala/coop/rchain/casper/engine/Engine.scala
  casper/src/main/scala/coop/rchain/casper/engine/GenesisCeremonyMaster.scala
  casper/src/main/scala/coop/rchain/casper/engine/Initializing.scala
  casper/src/main/scala/coop/rchain/casper/engine/LfsBlockRequester.scala
  casper/src/main/scala/coop/rchain/casper/engine/LfsTupleSpaceRequester.scala
  casper/src/main/scala/coop/rchain/casper/engine/Running.scala
  casper/src/main/scala/coop/rchain/casper/util/comm/CommUtil.scala
  casper/src/test/scala/coop/rchain/casper/engine/GenesisCeremonyMasterSpec.scala
  casper/src/test/scala/coop/rchain/casper/engine/InitializingSpec.scala
  node/src/main/resources/defaults.conf
  node/src/main/scala/coop/rchain/node/Main.scala
  node/src/main/scala/coop/rchain/node/NodeRuntime.scala
  node/src/main/scala/coop/rchain/node/configuration/commandline/ConfigMapper.scala
  node/src/main/scala/coop/rchain/node/configuration/commandline/Options.scala
  node/src/main/scala/coop/rchain/node/configuration/model.scala
  node/src/main/scala/coop/rchain/node/web/package.scala
  node/src/test/scala/coop/rchain/node/configuration/commandline/ConfigMapperSpec.scala
  node/src/test/scala/coop/rchain/node/configuration/hocon/HoconConfigurationSpec.scala
  shared/src/main/scala/coop/rchain/fs2/Fs2StreamSyntax.scala
Labels: bug-fix, feature-branch

#3274 Fix synchrony constraint to use main parent weight map
  casper/src/main/scala/coop/rchain/casper/SynchronyConstraintChecker.scala
Labels: bug-fix

#3132 Add trim state integration tests
  integration-tests/test/test_trim_state.py
Labels: build-tests-ci, feature-branch

#3276 Add default MDB_NORDAHEAD flag to LMDB environment
  block-storage/src/main/scala/coop/rchain/blockstorage/dag/BlockDagFileStorage.scala
  block-storage/src/main/scala/coop/rchain/blockstorage/deploy/LMDBDeployStorage.scala
  casper/src/main/scala/coop/rchain/casper/storage/LmdbStoreManager.scala
  rspace-bench/src/test/scala/coop/rchain/lmdb/LMDBOpsBench.scala
  rspace/src/main/scala/coop/rchain/rspace/Context.scala
  rspace/src/main/scala/coop/rchain/rspace/history/Store.scala
  rspace/src/test/scala/coop/rchain/rspace/ReplayRSpaceTests.scala
  rspace/src/test/scala/coop/rchain/rspace/StorageTestsBase.scala
  rspace/src/test/scala/coop/rchain/rspace/history/HistoryRepositoryGenerativeSpec.scala
Labels: enhancement

#3204 StateMerger spec
  casper/src/main/scala/coop/rchain/casper/EstimatorHelper.scala
  casper/src/test/scala/coop/rchain/casper/batch1/MergeabilityRules.scala
  casper/src/test/scala/coop/rchain/casper/batch1/MultiParentCasperMergeSpec.scala
  casper/src/test/scala/coop/rchain/casper/batch1/StateMergerSpec.scala
  casper/src/test/scala/coop/rchain/casper/helper/TestRhoRuntime.scala
  rholang/src/main/scala/coop/rchain/rholang/interpreter/RhoRuntime.scala
  rholang/src/test/scala/coop/rchain/rholang/Resources.scala
  rholang/src/test/scala/coop/rchain/rholang/interpreter/storage/ISpaceStub.scala
  rspace/src/main/scala/coop/rchain/rspace/Hasher.scala
  rspace/src/main/scala/coop/rchain/rspace/ISpace.scala
  rspace/src/main/scala/coop/rchain/rspace/RSpace.scala
  rspace/src/main/scala/coop/rchain/rspace/RSpaceOps.scala
  rspace/src/main/scala/coop/rchain/rspace/channelStore/ChannelStore.scala
  rspace/src/main/scala/coop/rchain/rspace/channelStore/instances/ChannelStoreImpl.scala
  rspace/src/main/scala/coop/rchain/rspace/history/HistoryHashReader.scala
  rspace/src/main/scala/coop/rchain/rspace/history/HistoryRepository.scala
  rspace/src/main/scala/coop/rchain/rspace/history/HistoryRepositoryImpl.scala
  rspace/src/main/scala/coop/rchain/rspace/history/syntax/HistoryRepositorySyntax.scala
  rspace/src/main/scala/coop/rchain/rspace/merger/StateMerger.scala
  rspace/src/main/scala/coop/rchain/rspace/merger/instances/StateMergerImpl.scala
  rspace/src/main/scala/coop/rchain/rspace/package.scala
  rspace/src/main/scala/coop/rchain/rspace/trace/Event.scala
  rspace/src/main/scala/coop/rchain/rspace/trace/TuplespaceEvent.scala
  rspace/src/test/scala/coop/rchain/rspace/ReplayRSpaceTests.scala
  rspace/src/test/scala/coop/rchain/rspace/StorageTestsBase.scala
  rspace/src/test/scala/coop/rchain/rspace/history/HistoryRepositoryGenerativeSpec.scala
  rspace/src/test/scala/coop/rchain/rspace/history/HistoryRepositorySpec.scala
Labels: feature-branch

#3201 Block processing refactor + casper refactor
  block-storage/src/main/scala/coop/rchain/blockstorage/casperbuffer/CasperBufferKeyValueStorage.scala
  block-storage/src/main/scala/coop/rchain/blockstorage/casperbuffer/CasperBufferStorage.scala
  block-storage/src/main/scala/coop/rchain/blockstorage/dag/BlockDagRepresentationSyntax.scala
  casper/src/main/scala/coop/rchain/casper/BlockCreator.scala
  casper/src/main/scala/coop/rchain/casper/BlockStatus.scala
  casper/src/main/scala/coop/rchain/casper/Casper.scala
  casper/src/main/scala/coop/rchain/casper/CreateBlockStatus.scala
  casper/src/main/scala/coop/rchain/casper/Estimator.scala
  casper/src/main/scala/coop/rchain/casper/LastFinalizedHeightConstraintChecker.scala
  casper/src/main/scala/coop/rchain/casper/MultiParentCasperImpl.scala
  casper/src/main/scala/coop/rchain/casper/SynchronyConstraintChecker.scala
  casper/src/main/scala/coop/rchain/casper/Validate.scala
  casper/src/main/scala/coop/rchain/casper/api/BlockAPI.scala
  casper/src/main/scala/coop/rchain/casper/blocks/BlockProcessor.scala
  casper/src/main/scala/coop/rchain/casper/blocks/proposer/BlockCreator.scala
  casper/src/main/scala/coop/rchain/casper/blocks/proposer/ProposeResult.scala
  casper/src/main/scala/coop/rchain/casper/blocks/proposer/Proposer.scala
  casper/src/main/scala/coop/rchain/casper/engine/CasperLaunch.scala
  casper/src/main/scala/coop/rchain/casper/engine/Engine.scala
  casper/src/main/scala/coop/rchain/casper/engine/GenesisCeremonyMaster.scala
  casper/src/main/scala/coop/rchain/casper/engine/GenesisValidator.scala
  casper/src/main/scala/coop/rchain/casper/engine/Initializing.scala
  casper/src/main/scala/coop/rchain/casper/engine/Running.scala
  casper/src/main/scala/coop/rchain/casper/state/instances/ProposerState.scala
  casper/src/main/scala/coop/rchain/casper/util/ProtoUtil.scala
  casper/src/main/scala/coop/rchain/casper/util/comm/ProposeService.scala
  casper/src/slowcooker/scala/coop.rchain.casper/HashSetCasperSpecification.scala
  casper/src/test/scala/coop/rchain/casper/addblock/MultiParentCasperAddBlockSpec.scala
  casper/src/test/scala/coop/rchain/casper/api/CreateBlockAPITest.scala
  casper/src/test/scala/coop/rchain/casper/batch1/MultiParentCasperCommunicationSpec.scala
  casper/src/test/scala/coop/rchain/casper/batch1/MultiParentCasperDeploySpec.scala
  casper/src/test/scala/coop/rchain/casper/batch1/MultiParentCasperMergeSpec.scala
  casper/src/test/scala/coop/rchain/casper/batch1/MultiParentCasperRholangSpec.scala
  casper/src/test/scala/coop/rchain/casper/batch2/SingleParentCasperSpec.scala
  casper/src/test/scala/coop/rchain/casper/engine/GenesisCeremonyMasterSpec.scala
  casper/src/test/scala/coop/rchain/casper/engine/GenesisValidatorSpec.scala
  casper/src/test/scala/coop/rchain/casper/engine/InitializingSpec.scala
  casper/src/test/scala/coop/rchain/casper/engine/RunningHandleBlockMessageSpec.scala
  casper/src/test/scala/coop/rchain/casper/engine/RunningHandleHasBlockSpec.scala
  casper/src/test/scala/coop/rchain/casper/engine/RunningSpec.scala
  casper/src/test/scala/coop/rchain/casper/engine/Setup.scala
  casper/src/test/scala/coop/rchain/casper/helper/NoOpsCasperEffect.scala
  casper/src/test/scala/coop/rchain/casper/helper/TestNode.scala
  casper/src/test/scala/coop/rchain/casper/util/rholang/Resources.scala
  integration-tests/Pipfile
  integration-tests/Pipfile.lock
  integration-tests/test/rnode.py
  integration-tests/test/test_slash.py
  models/src/main/protobuf/ProposeServiceCommon.proto
  models/src/main/protobuf/ProposeServiceV1.proto
  models/src/main/scala/coop/rchain/casper/PrettyPrinter.scala
  node/src/main/scala/coop/rchain/node/NodeRuntime.scala
  node/src/main/scala/coop/rchain/node/api/AdminWebApi.scala
  node/src/main/scala/coop/rchain/node/api/ProposeGrpcServiceV1.scala
  node/src/main/scala/coop/rchain/node/instances/BlockProcessorInstance.scala
  node/src/main/scala/coop/rchain/node/instances/ProposerInstance.scala
  node/src/main/scala/coop/rchain/node/web/package.scala
  node/src/test/scala/coop/rchain/node/web/WebApiRoutesTest.scala
Labels: feature-branch
