Repository rchain/rchain, pull requests merged in 2020-07, with the labels that each got.

#2985 fix explore deploy backward not compatible
  node/src/main/scala/coop/rchain/node/api/DeployGrpcServiceV1.scala
  node/src/main/scala/coop/rchain/node/web/WebApiRoutes.scala
Labels: bug-fix

#2990 RCHAIN-791: Fix node exit in terminal (input not visible)
  node/src/main/scala/coop/rchain/node/Main.scala
Labels: bug-fix

#2989 Fix LMDB store freeze - thread safety (part 2)
  casper/src/main/scala/coop/rchain/casper/storage/LmdbKeyValueStore.scala
Labels: bug-fix

#2991 RCHAIN-4092: Skip migration of DAG storage when node is empty
  node/src/main/scala/coop/rchain/node/NodeRuntime.scala
Labels: bug-fix

#2943 RCHAIN-4080: New block retrieval procedure + preparing for LFS
  block-storage/src/main/scala/coop/rchain/blockstorage/casperbuffer/CasperBufferKeyValueStorage.scala
  block-storage/src/main/scala/coop/rchain/blockstorage/casperbuffer/CasperBufferStorage.scala
  block-storage/src/main/scala/coop/rchain/blockstorage/dag/BlockDagKeyValueStorage.scala
  block-storage/src/main/scala/coop/rchain/blockstorage/dag/BlockDagStorage.scala
  block-storage/src/main/scala/coop/rchain/blockstorage/util/DoublyLinkedDagOperations.scala
  casper/src/main/scala/coop/rchain/casper/BlockStatus.scala
  casper/src/main/scala/coop/rchain/casper/Casper.scala
  casper/src/main/scala/coop/rchain/casper/EquivocationDetector.scala
  casper/src/main/scala/coop/rchain/casper/LastFinalizedBlockCalculator.scala
  casper/src/main/scala/coop/rchain/casper/MultiParentCasperImpl.scala
  casper/src/main/scala/coop/rchain/casper/ReportMemStore.scala
  casper/src/main/scala/coop/rchain/casper/Validate.scala
  casper/src/main/scala/coop/rchain/casper/api/BlockAPI.scala
  casper/src/main/scala/coop/rchain/casper/engine/BlockRetriever.scala
  casper/src/main/scala/coop/rchain/casper/engine/CasperLaunch.scala
  casper/src/main/scala/coop/rchain/casper/engine/Engine.scala
  casper/src/main/scala/coop/rchain/casper/engine/GenesisCeremonyMaster.scala
  casper/src/main/scala/coop/rchain/casper/engine/GenesisValidator.scala
  casper/src/main/scala/coop/rchain/casper/engine/Initializing.scala
  casper/src/main/scala/coop/rchain/casper/engine/Running.scala
  casper/src/main/scala/coop/rchain/casper/storage/LmdbStoreManager.scala
  casper/src/main/scala/coop/rchain/casper/storage/RNodeKeyValueStoreManager.scala
  casper/src/main/scala/coop/rchain/casper/util/comm/CasperPacketHandler.scala
  casper/src/main/scala/coop/rchain/casper/util/comm/CommUtil.scala
  casper/src/test/scala/coop/rchain/casper/addblock/MultiParentCasperAddBlockSpec.scala
  casper/src/test/scala/coop/rchain/casper/api/CreateBlockAPITest.scala
  casper/src/test/scala/coop/rchain/casper/api/PreviewPrivateNameTest.scala
  casper/src/test/scala/coop/rchain/casper/batch1/MultiParentCasperFinalizationSpec.scala
  casper/src/test/scala/coop/rchain/casper/engine/ApproveBlockProtocolTest.scala
  casper/src/test/scala/coop/rchain/casper/engine/RunningHandleBlockMessageSpec.scala
  casper/src/test/scala/coop/rchain/casper/engine/RunningHandleHasBlockSpec.scala
  casper/src/test/scala/coop/rchain/casper/engine/RunningMaintainRequestedBlocksSpec.scala
  casper/src/test/scala/coop/rchain/casper/engine/RunningSpec.scala
  casper/src/test/scala/coop/rchain/casper/engine/Setup.scala
  casper/src/test/scala/coop/rchain/casper/helper/NoOpsCasperEffect.scala
  casper/src/test/scala/coop/rchain/casper/helper/TestNode.scala
  casper/src/test/scala/coop/rchain/casper/util/GenesisBuilder.scala
  casper/src/test/scala/coop/rchain/casper/util/comm/CommUtilSpec.scala
  casper/src/test/scala/coop/rchain/casper/util/rholang/Resources.scala
  comm/src/test/scala/coop/rchain/p2p/EffectsTestInstances.scala
  models/src/main/scala/coop/rchain/casper/PrettyPrinter.scala
  node/src/main/scala/coop/rchain/node/NodeRuntime.scala
  rspace/src/main/scala/coop/rchain/rspace/history/StoreFactory.scala
  shared/src/main/scala/coop/rchain/shared/package.scala
  shared/src/main/scala/coop/rchain/store/InMemoryStoreManager.scala
  shared/src/main/scala/coop/rchain/store/KeyValueStoreManager.scala
  shared/src/main/scala/coop/rchain/store/KeyValueStoreManagerSyntax.scala
  shared/src/test/scala/coop/rchain/store/InMemoryKeyValueStoreSpec.scala
Labels: enhancement

#2950 RCHAIN-4098: fix malformed trie error with tests
  rspace/src/main/scala/coop/rchain/rspace/history/HistoryInstances.scala
  rspace/src/test/scala/coop/rchain/rspace/history/HistorySpec.scala
Labels: bug-fix

#2987 Improve error message in extension methods (unsafe get)
  block-storage/src/main/scala/coop/rchain/blockstorage/BlockStoreSyntax.scala
  block-storage/src/main/scala/coop/rchain/blockstorage/dag/BlockDagRepresentationSyntax.scala
Labels: enhancement

#3002 Prioritise pendant block when picking the next bock to add
  casper/src/main/scala/coop/rchain/casper/MultiParentCasperImpl.scala
Labels: bug-fix

#3000 Fix hash mismatch when joins are not sorted
  casper/src/test/scala/coop/rchain/casper/util/rholang/RuntimeManagerTest.scala
  rspace/src/main/scala/coop/rchain/rspace/history/HistoryRepositoryImpl.scala
  rspace/src/test/scala/coop/rchain/rspace/history/EncodingSpec.scala
Labels: bug-fix

#3006 Use one gRPC channel per peer
  comm/src/main/scala/coop/rchain/comm/transport/GrpcTransportClient.scala
  comm/src/test/scala/coop/rchain/comm/transport/TcpTransportLayerSpec.scala
  node/src/main/scala/coop/rchain/node/NodeRuntime.scala
  node/src/main/scala/coop/rchain/node/effects/package.scala
Labels: enhancement

#2998 Catch up optimisation tests
  block-storage/src/test/scala/coop/rchain/blockstorage/casperbuffer/CasperBufferStorageTest.scala
  block-storage/src/test/scala/coop/rchain/blockstorage/dag/BlockDagKeyValueStorageTest.scala
  block-storage/src/test/scala/coop/rchain/blockstorage/dag/BlockDagStorageTest.scala
  block-storage/src/test/scala/coop/rchain/blockstorage/finality/LastFinalizedFileStorageTest.scala
  casper/src/main/scala/coop/rchain/casper/BlockCreator.scala
  casper/src/main/scala/coop/rchain/casper/Validate.scala
  casper/src/main/scala/coop/rchain/casper/ValidatorIdentity.scala
  casper/src/main/scala/coop/rchain/casper/engine/BlockRetriever.scala
  casper/src/main/scala/coop/rchain/casper/engine/Running.scala
  casper/src/main/scala/coop/rchain/casper/util/ProtoUtil.scala
  casper/src/test/scala/coop/rchain/casper/addblock/MultiParentCasperAddBlockSpec.scala
  casper/src/test/scala/coop/rchain/casper/api/BlockQueryResponseAPITest.scala
  casper/src/test/scala/coop/rchain/casper/batch2/ValidateTest.scala
  casper/src/test/scala/coop/rchain/casper/engine/BlockApproverProtocolTest.scala
  casper/src/test/scala/coop/rchain/casper/engine/RunningHandleBlockMessageSpec.scala
  casper/src/test/scala/coop/rchain/casper/engine/RunningHandleHasBlockRequestSpec.scala
  casper/src/test/scala/coop/rchain/casper/engine/RunningHandleHasBlockSpec.scala
  casper/src/test/scala/coop/rchain/casper/engine/RunningMaintainRequestedBlocksSpec.scala
  casper/src/test/scala/coop/rchain/casper/engine/RunningSpec.scala
  casper/src/test/scala/coop/rchain/casper/engine/Setup.scala
  casper/src/test/scala/coop/rchain/casper/genesis/GenesisTest.scala
  casper/src/test/scala/coop/rchain/casper/helper/BlockGenerator.scala
  casper/src/test/scala/coop/rchain/casper/helper/BlockUtil.scala
  casper/src/test/scala/coop/rchain/casper/helper/NoOpsCasperEffect.scala
  casper/src/test/scala/coop/rchain/casper/helper/TestNode.scala
  casper/src/test/scala/coop/rchain/casper/sync/BlockRetrieverRequesAllSpec.scala
  casper/src/test/scala/coop/rchain/casper/sync/BlockRetrieverSpec.scala
  casper/src/test/scala/coop/rchain/casper/util/GenesisBuilder.scala
  casper/src/test/scala/coop/rchain/casper/util/ProtoUtilTest.scala
  casper/src/test/scala/coop/rchain/casper/util/rholang/InterpreterUtilTest.scala
  models/src/main/scala/coop/rchain/models/block/StateHash.scala
  models/src/test/scala/coop/rchain/casper/protocol/Dummies.scala
  models/src/test/scala/coop/rchain/models/blockImplicits.scala
  node/src/test/scala/coop/rchain/node/web/WebApiRoutesTest.scala
Labels: build-tests-ci
