Repository rchain/rchain, pull requests merged in 2020-06, with the labels that each got.

#2927 RCHAIN-4081: Specify a starting point to visualize dag
  casper/src/main/scala/coop/rchain/casper/api/BlockAPI.scala
  casper/src/test/scala/coop/rchain/casper/helper/TestNode.scala
  models/src/main/protobuf/DeployServiceCommon.proto
  node/src/main/scala/coop/rchain/node/api/DeployGrpcServiceV1.scala
Labels: next-release

#2934 RCHAIN-4077: Key-value store with manager
  block-storage/src/main/scala/coop/rchain/blockstorage/dag/BlockDagFileStorage.scala
  block-storage/src/main/scala/coop/rchain/blockstorage/dag/InMemBlockDagStorage.scala
  casper/src/main/scala/coop/rchain/casper/storage/LmdbKeyValueStore.scala
  casper/src/main/scala/coop/rchain/casper/storage/LmdbStoreManager.scala
  casper/src/main/scala/coop/rchain/casper/storage/RNodeKeyValueStoreManager.scala
  casper/src/test/scala/coop/rchain/casper/batch2/LmdbKeyValueStoreSpec.scala
  rspace/src/main/scala/coop/rchain/rspace/history/StoreFactory.scala
  shared/src/main/scala/coop/rchain/shared/AttemptOpsF.scala
  shared/src/main/scala/coop/rchain/shared/package.scala
  shared/src/main/scala/coop/rchain/store/InMemoryKeyValueStore.scala
  shared/src/main/scala/coop/rchain/store/InMemoryStoreManager.scala
  shared/src/main/scala/coop/rchain/store/KeyValueStore.scala
  shared/src/main/scala/coop/rchain/store/KeyValueStoreManager.scala
  shared/src/main/scala/coop/rchain/store/KeyValueStoreSyntax.scala
  shared/src/main/scala/coop/rchain/store/KeyValueTypedStore.scala
  shared/src/main/scala/coop/rchain/store/KeyValueTypedStoreCodec.scala
  shared/src/main/scala/coop/rchain/store/KeyValueTypedStoreSyntax.scala
  shared/src/test/scala/coop/rchain/store/InMemoryKeyValueStoreSpec.scala
Labels: next-release

#2918 RCHIP-11: Add bytesToHex method
  rholang/src/main/scala/coop/rchain/rholang/interpreter/Reduce.scala
  rholang/src/main/scala/coop/rchain/rholang/interpreter/accounting/Costs.scala
  rholang/src/test/scala/coop/rchain/rholang/interpreter/ReduceSpec.scala
  rholang/src/test/scala/coop/rchain/rholang/interpreter/accounting/RholangMethodsCostsSpec.scala
Labels: next-release

#2945 RCHAIN-4095: Fix slashing condition, not include Slashed deploy in every block
  casper/src/main/scala/coop/rchain/casper/BlockCreator.scala
  casper/src/main/scala/coop/rchain/casper/MultiParentCasperImpl.scala
  integration-tests/Pipfile
  integration-tests/Pipfile.lock
  integration-tests/test/rnode.py
  integration-tests/test/test_slash.py
Labels: next-release

#2947 RCHAIN-4103: Set fault tolerance as 1 for valid old blocks (temp solution)
  casper/src/main/scala/coop/rchain/casper/api/BlockAPI.scala
Labels: next-release

#2944 RCHAIN-4097: Improved Web API error handling, log response errors
  node/src/main/scala/coop/rchain/node/NodeRuntime.scala
  node/src/main/scala/coop/rchain/node/web/WebApiRoutes.scala
  node/src/main/scala/coop/rchain/node/web/package.scala
  node/src/test/scala/coop/rchain/node/web/WebApiRoutesTest.scala
  project/Dependencies.scala
Labels: next-release

#2942 RCHAIN-4084: Create HTTP Admin (internal) API endpoint
  README.md
  node/src/main/resources/defaults.conf
  node/src/main/scala/coop/rchain/node/Main.scala
  node/src/main/scala/coop/rchain/node/NodeRuntime.scala
  node/src/main/scala/coop/rchain/node/api/AdminWebApi.scala
  node/src/main/scala/coop/rchain/node/configuration/commandline/ConfigMapper.scala
  node/src/main/scala/coop/rchain/node/configuration/commandline/Options.scala
  node/src/main/scala/coop/rchain/node/configuration/model.scala
  node/src/main/scala/coop/rchain/node/web/AdminWebApiRoutes.scala
  node/src/main/scala/coop/rchain/node/web/package.scala
  node/src/test/scala/coop/rchain/node/configuration/commandline/ConfigMapperSpec.scala
  node/src/test/scala/coop/rchain/node/configuration/hocon/HoconConfigurationSpec.scala
  node/src/test/scala/coop/rchain/node/web/WebApiRoutesTest.scala
Labels: next-release

#2948 RCHAIN-4048: Limit the execution of exploratory deploy with phloLimit
  casper/src/main/scala/coop/rchain/casper/util/rholang/RuntimeManager.scala
Labels: next-release

#2935 RCHAIN-4092: DAG storage implementation with key-value store (LMDB)
  block-storage/src/main/scala/coop/rchain/blockstorage/dag/BlockDagFileStorage.scala
  block-storage/src/main/scala/coop/rchain/blockstorage/dag/BlockDagKeyValueStorage.scala
  block-storage/src/main/scala/coop/rchain/blockstorage/dag/BlockDagRepresentationSyntax.scala
  block-storage/src/main/scala/coop/rchain/blockstorage/dag/BlockDagStorage.scala
  block-storage/src/main/scala/coop/rchain/blockstorage/dag/BlockMetadataStore.scala
  block-storage/src/main/scala/coop/rchain/blockstorage/dag/EquivocationTrackerStore.scala
  block-storage/src/main/scala/coop/rchain/blockstorage/package.scala
  block-storage/src/test/scala/coop/rchain/blockstorage/dag/BlockDagKeyValueStorageTest.scala
  block-storage/src/test/scala/coop/rchain/blockstorage/dag/BlockDagStorageTest.scala
  block-storage/src/test/scala/coop/rchain/blockstorage/dag/IndexedBlockDagStorage.scala
  casper/src/main/scala/coop/rchain/casper/BlockCreator.scala
  casper/src/main/scala/coop/rchain/casper/LastFinalizedHeightConstraintChecker.scala
  casper/src/main/scala/coop/rchain/casper/SafetyOracle.scala
  casper/src/main/scala/coop/rchain/casper/Validate.scala
  casper/src/main/scala/coop/rchain/casper/api/BlockAPI.scala
  casper/src/main/scala/coop/rchain/casper/storage/RNodeKeyValueStoreManager.scala
  casper/src/main/scala/coop/rchain/casper/util/ProtoUtil.scala
  casper/src/test/scala/coop/rchain/casper/addblock/MultiParentCasperAddBlockSpec.scala
  casper/src/test/scala/coop/rchain/casper/batch1/MultiParentCasperMergeSpec.scala
  casper/src/test/scala/coop/rchain/casper/batch2/ValidateTest.scala
  casper/src/test/scala/coop/rchain/casper/helper/BlockDagStorageFixture.scala
  casper/src/test/scala/coop/rchain/casper/util/GenesisBuilder.scala
  casper/src/test/scala/coop/rchain/casper/util/rholang/Resources.scala
  node/src/main/scala/coop/rchain/node/NodeRuntime.scala
Labels: enhancement

#2955 InfluxDB config fix
  node/src/main/scala/coop/rchain/node/diagnostics/UdpInfluxDBReporter.scala
Labels: bug-fix

#2965 [v0.9.25] CI update workflow with release artifacts
  .github/workflows/continuous-integration.yml
Labels: build-tests-ci, feature-branch

#2964 Fix LMDB commit transaction when execution freezes
  .github/workflows/continuous-integration.yml
  casper/src/main/scala/coop/rchain/casper/storage/LmdbKeyValueStore.scala
  node/src/main/scala/coop/rchain/node/NodeRuntime.scala
  shared/src/main/scala/coop/rchain/store/InMemoryKeyValueStore.scala
  shared/src/main/scala/coop/rchain/store/KeyValueStore.scala
  shared/src/main/scala/coop/rchain/store/KeyValueTypedStoreCodec.scala
Labels: bug-fix

#2962 CI update workflow with release artifacts
  .github/workflows/continuous-integration.yml
Labels: build-tests-ci

#2959 RCHAIN-4087: Update issue templates for security bug report
  .github/ISSUE_TEMPLATE/20_bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/pull_request_template.md
Labels: build-tests-ci

#2952 RCHAIN-4109: Alignment + colors for logs
  integration-tests/test/wait.py
  node/src/main/resources/logback.xml
Labels: enhancement

#2958 Optimization of loading partial block data (BlockStore)
  block-storage/src/main/scala/coop/rchain/blockstorage/FileLMDBIndexBlockStore.scala
  casper/src/main/scala/coop/rchain/casper/LastFinalizedHeightConstraintChecker.scala
Labels: enhancement

#2967 RCHAIN-4111: provide block hash on exploratory deploy
  casper/src/main/scala/coop/rchain/casper/api/BlockAPI.scala
  casper/src/test/scala/coop/rchain/casper/api/ExploratoryDeployAPITest.scala
  models/src/main/protobuf/DeployServiceCommon.proto
  node/src/main/scala/coop/rchain/node/api/DeployGrpcServiceV1.scala
  node/src/main/scala/coop/rchain/node/api/WebApi.scala
  node/src/main/scala/coop/rchain/node/web/WebApiRoutes.scala
  node/src/test/scala/coop/rchain/node/web/WebApiRoutesTest.scala
Labels: enhancement

#2978 Fix closing LMDB environment only if open
  casper/src/main/scala/coop/rchain/casper/storage/LmdbStoreManager.scala
Labels: bug-fix

#2969 RCHAIN-4113 put justificationInfo in blockInfo
  casper/src/main/scala/coop/rchain/casper/api/BlockAPI.scala
  casper/src/main/scala/coop/rchain/casper/util/ProtoUtil.scala
  casper/src/test/scala/coop/rchain/casper/api/BlockQueryResponseAPITest.scala
  integration-tests/test/test_dag_correctness.py
  integration-tests/test/test_internal.py
  integration-tests/test/utils.py
  models/src/main/protobuf/DeployServiceCommon.proto
  node/src/test/scala/coop/rchain/node/web/WebApiRoutesTest.scala
Labels: enhancement

#2973 RCHAIN-3954: refactor integration test
  integration-tests/Dockerfile
  integration-tests/generate_rnode_data.py
  integration-tests/test/common.py
  integration-tests/test/error.py
  integration-tests/test/node_client.py
  integration-tests/test/rnode.py
  integration-tests/test/test_bonding_validators.py
  integration-tests/test/test_dag_correctness.py
  integration-tests/test/test_deployment.py
  integration-tests/test/test_genesis_ceremony.py
  integration-tests/test/test_internal.py
  integration-tests/test/test_propose.py
  integration-tests/test/test_slash.py
  integration-tests/test/test_synchrony_constraint.py
  integration-tests/test/test_unbond.py
  integration-tests/test/utils.py
  integration-tests/test/wait.py
Labels: enhancement, python

#2975 Reorganize TransportLayer, CommUtil, BlockStore helpers
  block-storage/src/main/scala/coop/rchain/blockstorage/BlockStore.scala
  block-storage/src/main/scala/coop/rchain/blockstorage/BlockStoreSyntax.scala
  block-storage/src/main/scala/coop/rchain/blockstorage/dag/BlockDagRepresentationSyntax.scala
  block-storage/src/main/scala/coop/rchain/blockstorage/package.scala
  casper/src/main/scala/coop/rchain/casper/BlockCreator.scala
  casper/src/main/scala/coop/rchain/casper/Casper.scala
  casper/src/main/scala/coop/rchain/casper/EquivocationDetector.scala
  casper/src/main/scala/coop/rchain/casper/Estimator.scala
  casper/src/main/scala/coop/rchain/casper/EstimatorHelper.scala
  casper/src/main/scala/coop/rchain/casper/LastFinalizedBlockCalculator.scala
  casper/src/main/scala/coop/rchain/casper/MultiParentCasperImpl.scala
  casper/src/main/scala/coop/rchain/casper/SynchronyConstraintChecker.scala
  casper/src/main/scala/coop/rchain/casper/Validate.scala
  casper/src/main/scala/coop/rchain/casper/api/BlockAPI.scala
  casper/src/main/scala/coop/rchain/casper/api/GraphGenerator.scala
  casper/src/main/scala/coop/rchain/casper/engine/CasperLaunch.scala
  casper/src/main/scala/coop/rchain/casper/engine/GenesisCeremonyMaster.scala
  casper/src/main/scala/coop/rchain/casper/engine/Initializing.scala
  casper/src/main/scala/coop/rchain/casper/engine/Running.scala
  casper/src/main/scala/coop/rchain/casper/package.scala
  casper/src/main/scala/coop/rchain/casper/util/ProtoUtil.scala
  casper/src/main/scala/coop/rchain/casper/util/comm/CommUtil.scala
  casper/src/main/scala/coop/rchain/casper/util/rholang/InterpreterUtil.scala
  comm/src/main/scala/coop/rchain/comm/package.scala
  comm/src/main/scala/coop/rchain/comm/transport/TransportLayerSyntax.scala
  node/src/main/scala/coop/rchain/node/NodeRuntime.scala
  rholang/src/main/scala/coop/rchain/rholang/interpreter/Reduce.scala
  rholang/src/main/scala/coop/rchain/rholang/interpreter/dispatch.scala
  rholang/src/test/scala/coop/rchain/rholang/interpreter/PersistentStoreTester.scala
  rholang/src/test/scala/coop/rchain/rholang/interpreter/RholangOnlyDispatcher.scala
  rholang/src/test/scala/coop/rchain/rholang/interpreter/accounting/RholangMethodsCostsSpec.scala
  shared/src/main/scala/coop/rchain/catscontrib/BooleanF.scala
  shared/src/main/scala/coop/rchain/shared/package.scala
  shared/src/main/scala/coop/rchain/store/KeyValueStoreSyntax.scala
  shared/src/main/scala/coop/rchain/store/KeyValueTypedStoreSyntax.scala
Labels: enhancement
