Repository rchain/rchain, pull requests merged in 2020-11, with the labels that each got.

#3202 Fix LMDB database corruption on put operation
  casper/src/main/scala/coop/rchain/casper/storage/LmdbKeyValueStore.scala
  rspace/src/main/scala/coop/rchain/rspace/history/Store.scala
  shared/src/main/scala/coop/rchain/lmdb/LMDBStore.scala
Labels: bug-fix

#3203 Fix LMDB get operation to safely use returned buffer
  block-storage/src/main/scala/coop/rchain/blockstorage/FileLMDBIndexBlockStore.scala
  block-storage/src/main/scala/coop/rchain/blockstorage/dag/BlockDagFileStorage.scala
  rspace/src/main/scala/coop/rchain/rspace/history/RootsStore.scala
  rspace/src/main/scala/coop/rchain/rspace/history/Store.scala
  rspace/src/main/scala/coop/rchain/rspace/history/StoreFactory.scala
  shared/src/main/scala/coop/rchain/lmdb/LMDBStore.scala
Labels: bug-fix

#3212 CI - upgrade to new way for set ENV variables
  .github/init-environment
Labels: build-tests-ci

#3214 Limit recursion depth in stack safe tests
  rholang/src/test/scala/coop/rchain/rholang/StackSafetySpec.scala
Labels: build-tests-ci

#3217 Fix interpreter test with non-deterministic comparison (failing on CI)
  rholang/src/test/scala/coop/rchain/rholang/InterpreterSpec.scala
Labels: bug-fix

#3145 Validation for LFS import
  build.sbt
  casper/src/main/scala/coop/rchain/casper/engine/Engine.scala
  casper/src/main/scala/coop/rchain/casper/engine/Initializing.scala
  casper/src/main/scala/coop/rchain/casper/engine/LastFinalizedStateBlockRequester.scala
  casper/src/main/scala/coop/rchain/casper/engine/LastFinalizedStateTupleSpaceRequester.scala
  casper/src/main/scala/coop/rchain/casper/engine/Running.scala
  casper/src/test/scala/coop/rchain/casper/engine/InitializingSpec.scala
  casper/src/test/scala/coop/rchain/casper/engine/LFSBlockRequesterEffectsSpec.scala
  casper/src/test/scala/coop/rchain/casper/engine/LFSBlockRequesterStateSpec.scala
  node/src/main/resources/logback.xml
  node/src/test/scala/coop/rchain/state/TrieExporterSpec.scala
  rspace/src/main/scala/coop/rchain/rspace/history/ColdStore.scala
  rspace/src/main/scala/coop/rchain/rspace/history/History.scala
  rspace/src/main/scala/coop/rchain/rspace/history/HistoryRepositoryImpl.scala
  rspace/src/main/scala/coop/rchain/rspace/history/HistoryStore.scala
  rspace/src/main/scala/coop/rchain/rspace/package.scala
  rspace/src/main/scala/coop/rchain/rspace/state/RSpaceExporter.scala
  rspace/src/main/scala/coop/rchain/rspace/state/RSpaceExporterSyntax.scala
  rspace/src/main/scala/coop/rchain/rspace/state/RSpaceImporter.scala
  rspace/src/main/scala/coop/rchain/rspace/state/exporters/RSpaceExporterDisk.scala
  rspace/src/main/scala/coop/rchain/rspace/state/exporters/RSpaceExporterItems.scala
  rspace/src/main/scala/coop/rchain/rspace/state/instances/RSpaceImporterImpl.scala
  rspace/src/main/scala/coop/rchain/rspace/state/syntax/package.scala
  rspace/src/test/scala/coop/rchain/rspace/history/HistoryRepositorySpec.scala
  shared/src/main/scala/coop/rchain/shared/Stopwatch.scala
Labels: enhancement, feature-branch

#3239 Transport layer in-memory cache
  casper/src/test/scala/coop/rchain/casper/helper/TestNode.scala
  casper/src/test/scala/coop/rchain/casper/util/comm/TransportLayerTestImpl.scala
  comm/src/main/scala/coop/rchain/comm/errors.scala
  comm/src/main/scala/coop/rchain/comm/transport/GrpcTransportClient.scala
  comm/src/main/scala/coop/rchain/comm/transport/GrpcTransportReceiver.scala
  comm/src/main/scala/coop/rchain/comm/transport/GrpcTransportServer.scala
  comm/src/main/scala/coop/rchain/comm/transport/PacketOps.scala
  comm/src/main/scala/coop/rchain/comm/transport/StreamHandler.scala
  comm/src/main/scala/coop/rchain/comm/transport/StreamObservable.scala
  comm/src/main/scala/coop/rchain/comm/transport/messages.scala
  comm/src/test/scala/coop/rchain/comm/transport/PacketStoreRestoreSpec.scala
  comm/src/test/scala/coop/rchain/comm/transport/StreamHandlerSpec.scala
  comm/src/test/scala/coop/rchain/comm/transport/TcpTransportLayerSpec.scala
  comm/src/test/scala/coop/rchain/comm/transport/TransportLayerRuntime.scala
  node/src/main/scala/coop/rchain/node/Main.scala
  node/src/main/scala/coop/rchain/node/NodeRuntime.scala
  node/src/main/scala/coop/rchain/node/effects/package.scala
  shared/src/main/scala/coop/rchain/shared/GracefulClose.scala
Labels: bug-fix

#3242 Sync LFS branch with dev
  casper/src/main/scala/coop/rchain/casper/ReportMemStore.scala
  casper/src/main/scala/coop/rchain/casper/ReportingCasper.scala
  casper/src/main/scala/coop/rchain/casper/engine/LastFinalizedStateTupleSpaceRequester.scala
  casper/src/test/scala/coop/rchain/casper/helper/TestNode.scala
  casper/src/test/scala/coop/rchain/casper/util/comm/TransportLayerTestImpl.scala
  comm/src/main/scala/coop/rchain/comm/errors.scala
  comm/src/main/scala/coop/rchain/comm/transport/GrpcTransportClient.scala
  comm/src/main/scala/coop/rchain/comm/transport/GrpcTransportReceiver.scala
  comm/src/main/scala/coop/rchain/comm/transport/GrpcTransportServer.scala
  comm/src/main/scala/coop/rchain/comm/transport/PacketOps.scala
  comm/src/main/scala/coop/rchain/comm/transport/StreamHandler.scala
  comm/src/main/scala/coop/rchain/comm/transport/StreamObservable.scala
  comm/src/main/scala/coop/rchain/comm/transport/messages.scala
  comm/src/test/scala/coop/rchain/comm/transport/PacketStoreRestoreSpec.scala
  comm/src/test/scala/coop/rchain/comm/transport/StreamHandlerSpec.scala
  comm/src/test/scala/coop/rchain/comm/transport/TcpTransportLayerSpec.scala
  comm/src/test/scala/coop/rchain/comm/transport/TransportLayerRuntime.scala
  node/src/main/scala/coop/rchain/node/Main.scala
  node/src/main/scala/coop/rchain/node/NodeRuntime.scala
  node/src/main/scala/coop/rchain/node/effects/package.scala
  rspace/src/main/scala/coop/rchain/rspace/RSpace.scala
  rspace/src/main/scala/coop/rchain/rspace/RSpaceOps.scala
  rspace/src/main/scala/coop/rchain/rspace/ReplayRSpace.scala
  rspace/src/main/scala/coop/rchain/rspace/ReportingRspace.scala
  rspace/src/main/scala/coop/rchain/rspace/util/package.scala
  rspace/src/test/scala/coop/rchain/rspace/HotStoreSpec.scala
  rspace/src/test/scala/coop/rchain/rspace/ReplayRSpaceTests.scala
  rspace/src/test/scala/coop/rchain/rspace/SerializeTests.scala
  rspace/src/test/scala/coop/rchain/rspace/StorageActionsTests.scala
  rspace/src/test/scala/coop/rchain/rspace/StorageExamplesTests.scala
  rspace/src/test/scala/coop/rchain/rspace/StorageTestsBase.scala
  rspace/src/test/scala/coop/rchain/rspace/history/EncodingSpec.scala
  rspace/src/test/scala/coop/rchain/rspace/history/HistoryRepositoryGenerativeSpec.scala
  shared/src/main/scala/coop/rchain/shared/GracefulClose.scala
  shared/src/main/scala/coop/rchain/shared/Serialize.scala
Labels: feature-branch

#3241 Fix signature verification for signing algorithm
  casper/src/test/scala/coop/rchain/casper/util/DeployValidationSpec.scala
  crypto/src/main/scala/coop/rchain/crypto/util/CertificateHelper.scala
Labels: bug-fix

#3243 Create height map when blocks are downloaded
  casper/src/main/scala/coop/rchain/casper/engine/Initializing.scala
  casper/src/main/scala/coop/rchain/casper/engine/LastFinalizedStateBlockRequester.scala
  casper/src/test/scala/coop/rchain/casper/engine/LFSBlockRequesterEffectsSpec.scala
Labels: enhancement

#3253 Updating dependencies
  build.sbt
  project/Dependencies.scala
  project/plugins.sbt
Labels: dependencies
