Repository rchain/rchain, pull requests merged in 2021-02, with the labels that each got.

#3303 Branch merger and conflict detector
  block-storage/src/main/scala/coop/rchain/blockstorage/dag/BlockDagFileStorage.scala
  block-storage/src/main/scala/coop/rchain/blockstorage/dag/BlockDagKeyValueStorage.scala
  block-storage/src/main/scala/coop/rchain/blockstorage/dag/BlockDagStorage.scala
  block-storage/src/main/scala/coop/rchain/blockstorage/dag/BlockMetadataStore.scala
  block-storage/src/main/scala/coop/rchain/blockstorage/dag/InMemBlockDagStorage.scala
  casper/src/main/scala/coop/rchain/casper/Casper.scala
  casper/src/main/scala/coop/rchain/casper/EquivocationDetector.scala
  casper/src/main/scala/coop/rchain/casper/Estimator.scala
  casper/src/main/scala/coop/rchain/casper/EstimatorHelper.scala
  casper/src/main/scala/coop/rchain/casper/MultiParentCasperImpl.scala
  casper/src/main/scala/coop/rchain/casper/SafetyOracle.scala
  casper/src/main/scala/coop/rchain/casper/Validate.scala
  casper/src/main/scala/coop/rchain/casper/blocks/BlockProcessor.scala
  casper/src/main/scala/coop/rchain/casper/blocks/merger/CasperDagMerger.scala
  casper/src/main/scala/coop/rchain/casper/blocks/merger/CasperMergingDagReader.scala
  casper/src/main/scala/coop/rchain/casper/blocks/merger/ConflictDetectors.scala
  casper/src/main/scala/coop/rchain/casper/blocks/merger/MergingVertex.scala
  casper/src/main/scala/coop/rchain/casper/blocks/proposer/BlockCreator.scala
  casper/src/main/scala/coop/rchain/casper/blocks/proposer/Proposer.scala
  casper/src/main/scala/coop/rchain/casper/util/ProtoUtil.scala
  casper/src/main/scala/coop/rchain/casper/util/rholang/InterpreterUtil.scala
  casper/src/main/scala/coop/rchain/casper/util/rholang/RuntimeManager.scala
  casper/src/test/scala/coop/rchain/casper/addblock/MultiParentCasperAddBlockSpec.scala
  casper/src/test/scala/coop/rchain/casper/batch1/MergeabilityRules.scala
  casper/src/test/scala/coop/rchain/casper/batch1/MultiParentCasperMergeSpec.scala
  casper/src/test/scala/coop/rchain/casper/batch1/StateMergerSpec.scala
  casper/src/test/scala/coop/rchain/casper/batch2/RholangBuildTest.scala
  casper/src/test/scala/coop/rchain/casper/batch2/ValidateTest.scala
  casper/src/test/scala/coop/rchain/casper/engine/BlockApproverProtocolTest.scala
  casper/src/test/scala/coop/rchain/casper/engine/Setup.scala
  casper/src/test/scala/coop/rchain/casper/genesis/GenesisTest.scala
  casper/src/test/scala/coop/rchain/casper/genesis/contracts/PoSSpec.scala
  casper/src/test/scala/coop/rchain/casper/helper/BlockGenerator.scala
  casper/src/test/scala/coop/rchain/casper/helper/NoOpsCasperEffect.scala
  casper/src/test/scala/coop/rchain/casper/helper/TestNode.scala
  casper/src/test/scala/coop/rchain/casper/util/DagOperationsTest.scala
  casper/src/test/scala/coop/rchain/casper/util/GenesisBuilder.scala
  casper/src/test/scala/coop/rchain/casper/util/rholang/InterpreterUtilTest.scala
  casper/src/test/scala/coop/rchain/casper/util/rholang/MergingBranchMergerSpec.scala
  casper/src/test/scala/coop/rchain/casper/util/rholang/Resources.scala
  casper/src/test/scala/coop/rchain/casper/util/rholang/RuntimeManagerTest.scala
  node/src/main/scala/coop/rchain/node/NodeRuntime.scala
  rholang/src/main/scala/coop/rchain/rholang/interpreter/RhoRuntime.scala
  rspace/src/main/scala/coop/rchain/rspace/Hasher.scala
  rspace/src/main/scala/coop/rchain/rspace/RSpace.scala
  rspace/src/main/scala/coop/rchain/rspace/history/HistoryHashReader.scala
  rspace/src/main/scala/coop/rchain/rspace/history/HistoryInstances.scala
  rspace/src/main/scala/coop/rchain/rspace/history/HistoryRepository.scala
  rspace/src/main/scala/coop/rchain/rspace/history/HistoryRepositoryImpl.scala
  rspace/src/main/scala/coop/rchain/rspace/history/syntax/HistoryRepositorySyntax.scala
  rspace/src/main/scala/coop/rchain/rspace/merger/StateMerger.scala
  rspace/src/main/scala/coop/rchain/rspace/merger/instances/StateMergerImpl.scala
  rspace/src/test/scala/coop/rchain/rspace/history/HistoryRepositoryGenerativeSpec.scala
  rspace/src/test/scala/coop/rchain/rspace/history/HistoryRepositorySpec.scala
  shared/src/main/scala/coop/rchain/dag/DagOps.scala
  shared/src/main/scala/coop/rchain/shared/DagOps.scala
  shared/src/main/scala/coop/rchain/store/LazyKeyValueCache.scala
Labels: enhancement, feature-branch

#3327 Revert CI workflows
  .github/workflows/checkmarx-analysis.yml
  .github/workflows/codacy-analysis.yml
  .github/workflows/crunch42-analysis.yml
  .github/workflows/snyk_infrastructure-analysis.yml
Labels: build-tests-ci

#3328 Optimization for in-memory block metadata store initialization
  block-storage/src/main/scala/coop/rchain/blockstorage/dag/BlockMetadataStore.scala
  shared/src/main/scala/coop/rchain/store/KeyValueTypedStore.scala
  shared/src/main/scala/coop/rchain/store/KeyValueTypedStoreCodec.scala
  shared/src/test/scala/coop/rchain/store/InMemoryKeyValueStoreSpec.scala
Labels: Priority-High, enhancement

#3330 Fix CI - Docker release tag and bors try
  .github/workflows/continuous-integration.yml
Labels: build-tests-ci
