Repository rchain/rchain, pull requests merged in 2021-06, with the labels that each got.

#3414 Send all tips on fork choice request
  casper/src/main/scala/coop/rchain/casper/Casper.scala
  casper/src/main/scala/coop/rchain/casper/engine/Running.scala
  casper/src/test/scala/coop/rchain/casper/engine/RunningSpec.scala
Labels: enhancement

#3417 Refactor Mergeability test cases
  casper/src/test/scala/coop/rchain/casper/batch1/BaseMergeability.scala
  casper/src/test/scala/coop/rchain/casper/batch1/JoinMergeability.scala
  casper/src/test/scala/coop/rchain/casper/batch1/MergeabilityRules.scala
  casper/src/test/scala/coop/rchain/casper/batch1/PeekMergeability.scala
  casper/src/test/scala/coop/rchain/casper/batch1/StateMergerSpec.scala
Labels: build-tests-ci, enhancement

#3419 Syntax for bytestring based models
  casper/src/main/scala/coop/rchain/casper/MultiParentCasperImpl.scala
  casper/src/main/scala/coop/rchain/casper/api/BlockAPI.scala
  casper/src/main/scala/coop/rchain/casper/util/rholang/costacc/PreChargeDeploy.scala
  casper/src/main/scala/coop/rchain/casper/util/rholang/costacc/RefundDeploy.scala
  casper/src/main/scala/coop/rchain/casper/util/rholang/costacc/SlashDeploy.scala
  casper/src/test/scala/coop/rchain/casper/api/BlockQueryResponseAPITest.scala
  models/src/main/scala/coop/rchain/models/BlockHash.scala
  models/src/main/scala/coop/rchain/models/ByteStringSyntax.scala
  models/src/main/scala/coop/rchain/models/block/StateHash.scala
  models/src/main/scala/coop/rchain/models/package.scala
  node/src/main/scala/coop/rchain/node/web/ReportingRoutes.scala
  rspace/src/main/scala/coop/rchain/rspace/merger/instances/EventLogIndexConflictDetector.scala
  shared/src/main/scala/coop/rchain/shared/package.scala
Labels: enhancement

#3422 Update feature/deploymerge branch with latest dev
  casper/src/main/scala/coop/rchain/casper/Casper.scala
  casper/src/main/scala/coop/rchain/casper/MultiParentCasperImpl.scala
  casper/src/main/scala/coop/rchain/casper/api/BlockAPI.scala
  casper/src/main/scala/coop/rchain/casper/blocks/proposer/BlockCreator.scala
  casper/src/main/scala/coop/rchain/casper/engine/Running.scala
  casper/src/main/scala/coop/rchain/casper/util/rholang/CasperRhoRuntimeSyntax.scala
  casper/src/main/scala/coop/rchain/casper/util/rholang/InterpreterUtil.scala
  casper/src/main/scala/coop/rchain/casper/util/rholang/costacc/PreChargeDeploy.scala
  casper/src/main/scala/coop/rchain/casper/util/rholang/costacc/RefundDeploy.scala
  casper/src/main/scala/coop/rchain/casper/util/rholang/costacc/SlashDeploy.scala
  casper/src/test/scala/coop/rchain/casper/api/BlockQueryResponseAPITest.scala
  casper/src/test/scala/coop/rchain/casper/batch1/BaseMergeability.scala
  casper/src/test/scala/coop/rchain/casper/batch1/JoinMergeability.scala
  casper/src/test/scala/coop/rchain/casper/batch1/MergeabilityRules.scala
  casper/src/test/scala/coop/rchain/casper/batch1/PeekMergeability.scala
  casper/src/test/scala/coop/rchain/casper/batch1/StateMergerSpec.scala
  casper/src/test/scala/coop/rchain/casper/engine/RunningSpec.scala
  models/src/main/scala/coop/rchain/models/BlockHash.scala
  models/src/main/scala/coop/rchain/models/ByteStringSyntax.scala
  models/src/main/scala/coop/rchain/models/block/StateHash.scala
  models/src/main/scala/coop/rchain/models/package.scala
  node/src/main/scala/coop/rchain/node/web/ReportingRoutes.scala
  rholang/reference_doc/data_structures/README.md
  shared/src/main/scala/coop/rchain/shared/package.scala
Labels: feature-branch

#3424 Enable join mergeablility cases
  casper/src/test/scala/coop/rchain/casper/batch1/JoinMergeability.scala
  rspace/src/main/scala/coop/rchain/rspace/merger/StateChangeMerger.scala
Labels: feature-branch

#3426 Remove obsolete in memory DAG storage
  block-storage/src/main/scala/coop/rchain/blockstorage/dag/InMemBlockDagStorage.scala
  casper/src/test/scala/coop/rchain/casper/engine/Setup.scala
Labels: enhancement

#3421 Clique oracle rewrite v2
  block-storage/src/main/scala/coop/rchain/blockstorage/dag/BlockDagKeyValueStorage.scala
  block-storage/src/main/scala/coop/rchain/blockstorage/dag/BlockDagRepresentationSyntax.scala
  block-storage/src/main/scala/coop/rchain/blockstorage/dag/BlockDagStorage.scala
  block-storage/src/main/scala/coop/rchain/blockstorage/dag/InMemBlockDagStorage.scala
  casper/src/main/scala/coop/rchain/casper/MultiParentCasperImpl.scala
  casper/src/main/scala/coop/rchain/casper/SafetyOracle.scala
  casper/src/main/scala/coop/rchain/casper/blocks/merger/CasperMergingDagReader.scala
  casper/src/main/scala/coop/rchain/casper/blocks/merger/MergingVertex.scala
  casper/src/main/scala/coop/rchain/casper/merging/ConflictSetMerger.scala
  casper/src/main/scala/coop/rchain/casper/merging/DagMerger.scala
  casper/src/main/scala/coop/rchain/casper/safety/CliqueOracle.scala
  casper/src/main/scala/coop/rchain/casper/util/ProtoUtil.scala
  casper/src/main/scala/coop/rchain/casper/util/rholang/InterpreterUtil.scala
  casper/src/test/scala/coop/rchain/casper/api/BlockQueryResponseAPITest.scala
  casper/src/test/scala/coop/rchain/casper/api/BlocksResponseAPITest.scala
  casper/src/test/scala/coop/rchain/casper/batch1/MergeabilityRules.scala
  casper/src/test/scala/coop/rchain/casper/batch2/CliqueOracleTest.scala
  casper/src/test/scala/coop/rchain/casper/util/CasperUtilTest.scala
  casper/src/test/scala/coop/rchain/casper/util/rholang/MergingBranchMergerSpec.scala
  casper/src/test/scala/coop/rchain/casper/util/rholang/Resources.scala
  models/src/test/scala/coop/rchain/models/blockImplicits.scala
  shared/src/main/scala/coop/rchain/dag/DagOps.scala
  shared/src/main/scala/coop/rchain/fs2/Fs2StreamSyntax.scala
Labels: feature-branch

#3428 Rename Rholang AST generated namespace & include BNFC generator in build compile step
  .github/workflows/continuous-integration.yml
  DEVELOPER.md
  README.md
  build.sbt
  casper/src/test/scala/coop/rchain/casper/batch1/MergeabilityRules.scala
  nix/README.md
  project/BNFC.scala
  project/plugins.sbt
  rholang/src/main/scala/coop/rchain/rholang/interpreter/RholangCLI.scala
  rholang/src/main/scala/coop/rchain/rholang/interpreter/compiler/ParBuilder.scala
  rholang/src/main/scala/coop/rchain/rholang/interpreter/compiler/normalize.scala
  rholang/src/main/scala/coop/rchain/rholang/interpreter/package.scala
  rholang/src/main/scala/coop/rchain/rholang/interpreter/storage/StoragePrinter.scala
  rholang/src/main/scala/coop/rchain/rholang/package.scala
  rholang/src/test/scala/coop/rchain/rholang/InterpreterSpec.scala
  rholang/src/test/scala/coop/rchain/rholang/ProcGen.scala
  rholang/src/test/scala/coop/rchain/rholang/ProcGenTest.scala
  rholang/src/test/scala/coop/rchain/rholang/StackSafetySpec.scala
  rholang/src/test/scala/coop/rchain/rholang/StoragePrinterSpec.scala
  rholang/src/test/scala/coop/rchain/rholang/interpreter/InterpreterUtil.scala
  rholang/src/test/scala/coop/rchain/rholang/interpreter/NormalizeTest.scala
  rholang/src/test/scala/coop/rchain/rholang/interpreter/ParBuilderUtil.scala
  rholang/src/test/scala/coop/rchain/rholang/interpreter/PrettyPrinterTest.scala
  rholang/src/test/scala/coop/rchain/rholang/interpreter/RuntimeSpec.scala
  rholang/src/test/scala/coop/rchain/rholang/interpreter/accounting/CostAccountingPropertyTest.scala
  rholang/src/test/scala/coop/rchain/rholang/interpreter/accounting/CostAccountingSpec.scala
  rholang/src/test/scala/rholang/rosette/CompilerTests.scala
Labels: build-tests-ci, documentation

#3411 Add command for getting balance from particular block
  build.sbt
  casper/src/main/scala/coop/rchain/casper/util/BondsParser.scala
  node/src/main/scala/coop/rchain/node/revvaultexport/RhoTrieTraverser.scala
  node/src/main/scala/coop/rchain/node/revvaultexport/StateBalances.scala
  node/src/main/scala/coop/rchain/node/revvaultexport/VaultBalanceGetter.scala
  node/src/main/scala/coop/rchain/node/revvaultexport/mainnet1/StateBalanceMain.scala
  node/src/main/scala/coop/rchain/node/revvaultexport/mainnet1/reporting/MergeBalanceMain.scala
  node/src/main/scala/coop/rchain/node/revvaultexport/mainnet1/reporting/PerValidatorVaults.scala
  node/src/main/scala/coop/rchain/node/revvaultexport/mainnet1/reporting/SpecialCase.scala
  node/src/main/scala/coop/rchain/node/revvaultexport/mainnet1/reporting/TransactionBalanceMain.scala
  node/src/main/scala/coop/rchain/node/revvaultexport/reporting/Transaction.scala
  node/src/main/scala/coop/rchain/node/revvaultexport/reporting/TransactionBalances.scala
  node/src/test/scala/coop/rchain/node/revvaultexport/RhoTrieTraverserTest.scala
  node/src/test/scala/coop/rchain/node/revvaultexport/TransactionParserTest.scala
  node/src/test/scala/coop/rchain/node/revvaultexport/VaultBalanceGetterTest.scala
  project/Dependencies.scala
Labels: enhancement

#3397 Make reporting replay system deploys
  casper/src/main/scala/coop/rchain/casper/ReportMemStore.scala
  casper/src/main/scala/coop/rchain/casper/ReportStore.scala
  casper/src/main/scala/coop/rchain/casper/ReportingCasper.scala
  casper/src/main/scala/coop/rchain/casper/api/BlockAPI.scala
  casper/src/main/scala/coop/rchain/casper/api/BlockReportAPI.scala
  casper/src/main/scala/coop/rchain/casper/util/rholang/CasperRhoRuntimeSyntax.scala
  casper/src/test/scala/coop/rchain/casper/batch1/MultiParentCasperReportingSpec.scala
  models/src/main/protobuf/DeployServiceCommon.proto
  models/src/main/protobuf/DeployServiceV1.proto
  node/src/main/scala/coop/rchain/node/api/DeployGrpcServiceV1.scala
  node/src/main/scala/coop/rchain/node/encode/JsonEncoder.scala
  node/src/main/scala/coop/rchain/node/runtime/APIServers.scala
  node/src/main/scala/coop/rchain/node/runtime/NodeRuntime.scala
  node/src/main/scala/coop/rchain/node/runtime/ServersInstances.scala
  node/src/main/scala/coop/rchain/node/runtime/Setup.scala
  node/src/main/scala/coop/rchain/node/web/AdminWebApiRoutes.scala
  node/src/main/scala/coop/rchain/node/web/ReportingRoutes.scala
  node/src/main/scala/coop/rchain/node/web/WebApiRoutes.scala
  node/src/main/scala/coop/rchain/node/web/package.scala
  node/src/test/scala/coop/rchain/node/web/WebApiRoutesTest.scala
  rspace/src/main/scala/coop/rchain/rspace/ReportingRspace.scala
Labels: enhancement

#3388 New finalizer with multi parent support
  block-storage/src/main/scala/coop/rchain/blockstorage/dag/BlockDagRepresentationSyntax.scala
  casper/src/main/scala/coop/rchain/casper/Casper.scala
  casper/src/main/scala/coop/rchain/casper/LastFinalizedBlockCalculator.scala
  casper/src/main/scala/coop/rchain/casper/MultiParentCasperImpl.scala
  casper/src/main/scala/coop/rchain/casper/engine/CasperLaunch.scala
  casper/src/main/scala/coop/rchain/casper/engine/Engine.scala
  casper/src/main/scala/coop/rchain/casper/engine/GenesisCeremonyMaster.scala
  casper/src/main/scala/coop/rchain/casper/engine/GenesisValidator.scala
  casper/src/main/scala/coop/rchain/casper/engine/Initializing.scala
  casper/src/main/scala/coop/rchain/casper/finality/Finalizer.scala
  casper/src/main/scala/coop/rchain/casper/safety/CliqueOracle.scala
  casper/src/test/scala/coop/rchain/casper/api/LastFinalizedAPITest.scala
  casper/src/test/scala/coop/rchain/casper/batch2/FinalizerTest.scala
  casper/src/test/scala/coop/rchain/casper/engine/Setup.scala
  casper/src/test/scala/coop/rchain/casper/helper/TestNode.scala
  node/src/main/scala/coop/rchain/node/runtime/Setup.scala
Labels: bug-fix, enhancement, feature-branch

#3429 Purge block index cache on finalization
  casper/src/main/scala/coop/rchain/casper/MultiParentCasperImpl.scala
Labels: enhancement

#3391 Refactor normalizer in separate files
  rholang/src/main/scala/coop/rchain/rholang/interpreter/compiler/normalize.scala
  rholang/src/main/scala/coop/rchain/rholang/interpreter/compiler/normalizer/BoolNormalizeMatcher.scala
  rholang/src/main/scala/coop/rchain/rholang/interpreter/compiler/normalizer/CollectionNormalizeMatcher.scala
  rholang/src/main/scala/coop/rchain/rholang/interpreter/compiler/normalizer/GroundNormalizeMatcher.scala
  rholang/src/main/scala/coop/rchain/rholang/interpreter/compiler/normalizer/NameNormalizeMatcher.scala
  rholang/src/main/scala/coop/rchain/rholang/interpreter/compiler/normalizer/RemainderNormalizeMatcher.scala
  rholang/src/main/scala/coop/rchain/rholang/interpreter/compiler/normalizer/processes/PBundleNormalizer.scala
  rholang/src/main/scala/coop/rchain/rholang/interpreter/compiler/normalizer/processes/PCollectNormalizer.scala
  rholang/src/main/scala/coop/rchain/rholang/interpreter/compiler/normalizer/processes/PConjunctionNormalizer.scala
  rholang/src/main/scala/coop/rchain/rholang/interpreter/compiler/normalizer/processes/PContrNormalizer.scala
  rholang/src/main/scala/coop/rchain/rholang/interpreter/compiler/normalizer/processes/PDisjunctionNormalizer.scala
  rholang/src/main/scala/coop/rchain/rholang/interpreter/compiler/normalizer/processes/PEvalNormalizer.scala
  rholang/src/main/scala/coop/rchain/rholang/interpreter/compiler/normalizer/processes/PGroundNormalizer.scala
  rholang/src/main/scala/coop/rchain/rholang/interpreter/compiler/normalizer/processes/PIfNormalizer.scala
  rholang/src/main/scala/coop/rchain/rholang/interpreter/compiler/normalizer/processes/PInputNormalizer.scala
  rholang/src/main/scala/coop/rchain/rholang/interpreter/compiler/normalizer/processes/PMatchNormalizer.scala
  rholang/src/main/scala/coop/rchain/rholang/interpreter/compiler/normalizer/processes/PMatchesNormalizer.scala
  rholang/src/main/scala/coop/rchain/rholang/interpreter/compiler/normalizer/processes/PMethodNormalizer.scala
  rholang/src/main/scala/coop/rchain/rholang/interpreter/compiler/normalizer/processes/PNegationNormalizer.scala
  rholang/src/main/scala/coop/rchain/rholang/interpreter/compiler/normalizer/processes/PNewNormalizer.scala
  rholang/src/main/scala/coop/rchain/rholang/interpreter/compiler/normalizer/processes/PParNormalizer.scala
  rholang/src/main/scala/coop/rchain/rholang/interpreter/compiler/normalizer/processes/PSendNormalizer.scala
  rholang/src/main/scala/coop/rchain/rholang/interpreter/compiler/normalizer/processes/PSimpleTypeNormalizer.scala
  rholang/src/main/scala/coop/rchain/rholang/interpreter/compiler/normalizer/processes/PVarNormalizer.scala
  rholang/src/main/scala/coop/rchain/rholang/interpreter/compiler/normalizer/processes/PVarRefNormalizer.scala
  rholang/src/main/scala/coop/rchain/rholang/interpreter/compiler/normalizer/processes/Utils.scala
  rholang/src/test/scala/coop/rchain/rholang/interpreter/PrettyPrinterTest.scala
  rholang/src/test/scala/coop/rchain/rholang/interpreter/compiler/normalizer/BoolMatcherSpec.scala
  rholang/src/test/scala/coop/rchain/rholang/interpreter/compiler/normalizer/CollectMatcherSpec.scala
  rholang/src/test/scala/coop/rchain/rholang/interpreter/compiler/normalizer/GroundMatcherSpec.scala
  rholang/src/test/scala/coop/rchain/rholang/interpreter/compiler/normalizer/NameMatcherSpec.scala
  rholang/src/test/scala/coop/rchain/rholang/interpreter/compiler/normalizer/ProcMatcherSpec.scala
Labels: enhancement

#3435 Fix LFS block requester tests
  casper/src/test/scala/coop/rchain/casper/engine/LfsBlockRequesterEffectsSpec.scala
  casper/src/test/scala/coop/rchain/casper/engine/LfsStateRequesterEffectsSpec.scala
  casper/src/test/scala/coop/rchain/casper/util/scalatest/Fs2StreamMatchers.scala
Labels: build-tests-ci

#3444 Fix rejection options bug. Refactor.
  casper/src/main/scala/coop/rchain/casper/merging/BlockIndex.scala
  casper/src/main/scala/coop/rchain/casper/merging/ConflictSetMerger.scala
  casper/src/main/scala/coop/rchain/casper/merging/DeployChainIndex.scala
  casper/src/test/scala/coop/rchain/casper/util/rholang/MergingBranchMergerSpec.scala
  rspace/src/main/scala/coop/rchain/rspace/merger/EventLogIndex.scala
  rspace/src/main/scala/coop/rchain/rspace/merger/MergingLogic.scala
  rspace/src/main/scala/coop/rchain/rspace/merger/StateChange.scala
  rspace/src/main/scala/coop/rchain/rspace/merger/package.scala
Labels: bug, feature-branch

#3451 Disable block indexing for single parent
  casper/src/main/scala/coop/rchain/casper/MultiParentCasperImpl.scala
Labels: bug-fix
