Repository rchain/rchain, pull requests merged in 2021-07, with the labels that each got.

#3459 Migrate LFB from LastFinalisedStore to BlockDagStorage
  block-storage/src/main/scala/coop/rchain/blockstorage/dag/BlockDagKeyValueStorage.scala
  block-storage/src/main/scala/coop/rchain/blockstorage/dag/BlockDagStorage.scala
  block-storage/src/main/scala/coop/rchain/blockstorage/dag/BlockMetadataStore.scala
  block-storage/src/main/scala/coop/rchain/blockstorage/finality/LastFinalizedKeyValueStorage.scala
  block-storage/src/main/scala/coop/rchain/blockstorage/finality/LastFinalizedMemoryStorage.scala
  block-storage/src/main/scala/coop/rchain/blockstorage/finality/LastFinalizedStorage.scala
  block-storage/src/main/scala/coop/rchain/blockstorage/package.scala
  block-storage/src/test/scala/coop/rchain/blockstorage/dag/BlockDagKeyValueStorageTest.scala
  block-storage/src/test/scala/coop/rchain/blockstorage/dag/BlockDagStorageTest.scala
  block-storage/src/test/scala/coop/rchain/blockstorage/dag/IndexedBlockDagStorage.scala
  casper/src/main/scala/coop/rchain/casper/Casper.scala
  casper/src/main/scala/coop/rchain/casper/LastFinalizedHeightConstraintChecker.scala
  casper/src/main/scala/coop/rchain/casper/MultiParentCasperImpl.scala
  casper/src/main/scala/coop/rchain/casper/blocks/proposer/Proposer.scala
  casper/src/main/scala/coop/rchain/casper/engine/CasperLaunch.scala
  casper/src/main/scala/coop/rchain/casper/engine/Engine.scala
  casper/src/main/scala/coop/rchain/casper/engine/GenesisCeremonyMaster.scala
  casper/src/main/scala/coop/rchain/casper/engine/GenesisValidator.scala
  casper/src/main/scala/coop/rchain/casper/engine/Initializing.scala
  casper/src/main/scala/coop/rchain/casper/engine/Running.scala
  casper/src/main/scala/coop/rchain/casper/finality/Finalizer.scala
  casper/src/test/scala/coop/rchain/casper/api/BlockQueryResponseAPITest.scala
  casper/src/test/scala/coop/rchain/casper/api/BlocksResponseAPITest.scala
  casper/src/test/scala/coop/rchain/casper/batch1/MergeabilityRules.scala
  casper/src/test/scala/coop/rchain/casper/batch2/FinalizerTest.scala
  casper/src/test/scala/coop/rchain/casper/batch2/ValidateTest.scala
  casper/src/test/scala/coop/rchain/casper/engine/RunningSpec.scala
  casper/src/test/scala/coop/rchain/casper/genesis/GenesisTest.scala
  casper/src/test/scala/coop/rchain/casper/helper/BlockDagStorageFixture.scala
  casper/src/test/scala/coop/rchain/casper/helper/TestNode.scala
  casper/src/test/scala/coop/rchain/casper/util/GenesisBuilder.scala
  casper/src/test/scala/coop/rchain/casper/util/rholang/MergingBranchMergerSpec.scala
  casper/src/test/scala/coop/rchain/casper/util/rholang/Resources.scala
  models/src/main/protobuf/CasperMessage.proto
  models/src/main/scala/coop/rchain/models/BlockMetadata.scala
  node/src/main/scala/coop/rchain/node/runtime/NodeRuntime.scala
  node/src/main/scala/coop/rchain/node/runtime/Setup.scala
  shared/src/main/scala/coop/rchain/store/KeyValueTypedStoreSyntax.scala
Labels: enhancement, feature-branch

#3440 Repairing bundle error message
  casper/src/test/scala/coop/rchain/casper/engine/LfsBlockRequesterEffectsSpec.scala
  rholang/src/main/scala/coop/rchain/rholang/interpreter/compiler/normalizer/processes/PBundleNormalizer.scala
Labels: bug-fix

#3464 Simplify bonds and wallets file parser
  block-storage/src/main/scala/coop/rchain/blockstorage/util/io/FileInputStreamIO.scala
  block-storage/src/main/scala/coop/rchain/blockstorage/util/io/FileOutputStreamIO.scala
  block-storage/src/main/scala/coop/rchain/blockstorage/util/io/SourceIO.scala
  build.sbt
  casper/src/main/scala/coop/rchain/casper/engine/ApproveBlockProtocol.scala
  casper/src/main/scala/coop/rchain/casper/engine/CasperLaunch.scala
  casper/src/main/scala/coop/rchain/casper/util/BondsParser.scala
  casper/src/main/scala/coop/rchain/casper/util/ProtoUtil.scala
  casper/src/main/scala/coop/rchain/casper/util/VaultParser.scala
  casper/src/main/scala/coop/rchain/casper/util/implicits.scala
  casper/src/test/scala/coop/rchain/casper/genesis/GenesisTest.scala
  casper/src/test/scala/coop/rchain/casper/helper/BlockUtil.scala
  node/src/main/scala/coop/rchain/node/revvaultexport/reporting/TransactionBalances.scala
  node/src/main/scala/coop/rchain/node/runtime/Setup.scala
  project/Dependencies.scala
Labels: enhancement

#3468 Make relation predicate to be non directional for merging logic.
  casper/src/main/scala/coop/rchain/casper/merging/BlockIndex.scala
  casper/src/main/scala/coop/rchain/casper/merging/ConflictSetMerger.scala
  casper/src/main/scala/coop/rchain/casper/merging/DeployChainIndex.scala
  casper/src/test/scala/coop/rchain/casper/merging/MergingCases.scala
  rspace/src/main/scala/coop/rchain/rspace/merger/MergingLogic.scala
Labels: bug-fix

#3472 Fix sync and migration on compacted state
  block-storage/src/main/scala/coop/rchain/blockstorage/finality/LastFinalizedKeyValueStorage.scala
  casper/src/main/scala/coop/rchain/casper/engine/Initializing.scala
Labels: bug-fix

#3470 Populate channels map in batch
  rspace/src/main/scala/coop/rchain/rspace/channelStore/ChannelStore.scala
  rspace/src/main/scala/coop/rchain/rspace/channelStore/instances/ChannelStoreImpl.scala
  rspace/src/main/scala/coop/rchain/rspace/history/HistoryRepositoryImpl.scala
  rspace/src/test/scala/coop/rchain/rspace/history/HistoryRepositorySpec.scala
Labels: enhancement

#3430 Add treeHashMap mergebility test
  casper/src/main/scala/coop/rchain/casper/merging/DagMerger.scala
  casper/src/main/scala/coop/rchain/casper/util/rholang/InterpreterUtil.scala
  casper/src/test/scala/coop/rchain/casper/batch1/MergeabilityRules.scala
  casper/src/test/scala/coop/rchain/casper/helper/TestRhoRuntime.scala
  node/src/test/scala/coop/rchain/node/mergeablity/BaseMergeability.scala
  node/src/test/scala/coop/rchain/node/mergeablity/ComputeMerge.scala
  node/src/test/scala/coop/rchain/node/mergeablity/JoinMergeability.scala
  node/src/test/scala/coop/rchain/node/mergeablity/MergeabilityRules.scala
  node/src/test/scala/coop/rchain/node/mergeablity/MergingBranchMergerSpec.scala
  node/src/test/scala/coop/rchain/node/mergeablity/PeekMergeability.scala
  node/src/test/scala/coop/rchain/node/mergeablity/TreeHashMapMergeabilitySpec.scala
  node/src/test/scala/coop/rchain/node/revvaultexport/RhoTrieTraverserTest.scala
  rholang/src/test/scala/coop/rchain/rholang/Resources.scala
Labels: build-tests-ci, enhancement, feature-branch

#3473 Preparatory snapshot on block 896988
  wallets_REV_BLOCK-896988.txt
Labels: documentation

#3466 RuntimeManager and Runtime cleanup
  casper/src/main/scala/coop/rchain/casper/ReportingCasper.scala
  casper/src/main/scala/coop/rchain/casper/util/rholang/RuntimeManager.scala
  casper/src/test/scala/coop/rchain/casper/batch2/ValidateTest.scala
  casper/src/test/scala/coop/rchain/casper/engine/Setup.scala
  casper/src/test/scala/coop/rchain/casper/genesis/GenesisTest.scala
  casper/src/test/scala/coop/rchain/casper/helper/BlockDagStorageFixture.scala
  casper/src/test/scala/coop/rchain/casper/helper/RhoSpec.scala
  casper/src/test/scala/coop/rchain/casper/helper/TestNode.scala
  casper/src/test/scala/coop/rchain/casper/util/GenesisBuilder.scala
  casper/src/test/scala/coop/rchain/casper/util/rholang/Interactive.scala
  casper/src/test/scala/coop/rchain/casper/util/rholang/Resources.scala
  casper/src/test/scala/coop/rchain/casper/util/rholang/RuntimeManagerTest.scala
  casper/src/test/scala/coop/rchain/casper/util/rholang/RuntimeSpec.scala
  node/src/main/scala/coop/rchain/node/revvaultexport/StateBalances.scala
  node/src/main/scala/coop/rchain/node/revvaultexport/mainnet1/reporting/MergeBalanceMain.scala
  node/src/main/scala/coop/rchain/node/revvaultexport/reporting/TransactionBalances.scala
  node/src/main/scala/coop/rchain/node/runtime/Setup.scala
  node/src/test/scala/coop/rchain/node/revvaultexport/VaultBalanceGetterTest.scala
  rholang/src/main/scala/coop/rchain/rholang/interpreter/RhoRuntime.scala
  rholang/src/main/scala/coop/rchain/rholang/interpreter/RholangCLI.scala
  rholang/src/main/scala/coop/rchain/rholang/interpreter/accounting/package.scala
  rholang/src/main/scala/coop/rchain/rholang/interpreter/storage/package.scala
  rholang/src/test/scala/coop/rchain/rholang/Resources.scala
  rholang/src/test/scala/coop/rchain/rholang/interpreter/CryptoChannelsSpec.scala
  rholang/src/test/scala/coop/rchain/rholang/interpreter/accounting/CostAccountingSpec.scala
  rspace-bench/src/test/scala/coop/rchain/rspace/bench/EvalBenchStateBase.scala
  rspace-bench/src/test/scala/coop/rchain/rspace/bench/ReplayRSpaceBench.scala
  rspace-bench/src/test/scala/coop/rchain/rspace/bench/RhoBenchBaseState.scala
  rspace/src/main/scala/coop/rchain/rspace/RSpace.scala
  rspace/src/main/scala/coop/rchain/rspace/RSpaceOps.scala
  rspace/src/main/scala/coop/rchain/rspace/ReplayRSpace.scala
  rspace/src/main/scala/coop/rchain/rspace/ReportingRspace.scala
  rspace/src/test/scala/coop/rchain/rspace/StorageActionsTests.scala
Labels: enhancement

#3462 Fix genesis blockhash validation bug
  casper/src/main/scala/coop/rchain/casper/Validate.scala
  casper/src/main/scala/coop/rchain/casper/ValidatorIdentity.scala
  casper/src/main/scala/coop/rchain/casper/blocks/proposer/BlockCreator.scala
  casper/src/main/scala/coop/rchain/casper/genesis/Genesis.scala
  casper/src/main/scala/coop/rchain/casper/util/ProtoUtil.scala
  casper/src/main/scala/coop/rchain/casper/util/rholang/CasperRhoRuntimeSyntax.scala
  casper/src/main/scala/coop/rchain/casper/util/rholang/RuntimeManager.scala
  casper/src/test/scala/coop/rchain/casper/batch2/ValidateTest.scala
  casper/src/test/scala/coop/rchain/casper/helper/BlockUtil.scala
Labels: bug-fix, feature-branch

#3458 Add system deploys to merging
  casper/src/main/scala/coop/rchain/casper/MultiParentCasperImpl.scala
  casper/src/main/scala/coop/rchain/casper/merging/BlockIndex.scala
  casper/src/main/scala/coop/rchain/casper/merging/DeployIndex.scala
  casper/src/main/scala/coop/rchain/casper/util/rholang/InterpreterUtil.scala
  casper/src/test/scala/coop/rchain/casper/merging/MergingCases.scala
  node/src/test/scala/coop/rchain/node/mergeablity/ComputeMerge.scala
  node/src/test/scala/coop/rchain/node/mergeablity/MergingBranchMergerSpec.scala
Labels: enhancement, feature-branch

#3474 Remove channels map
  casper/src/main/scala/coop/rchain/casper/api/BlockAPI.scala
  casper/src/main/scala/coop/rchain/casper/merging/BlockIndex.scala
  casper/src/main/scala/coop/rchain/casper/merging/ConflictSetMerger.scala
  casper/src/main/scala/coop/rchain/casper/merging/DagMerger.scala
  casper/src/main/scala/coop/rchain/casper/merging/DeployChainIndex.scala
  casper/src/main/scala/coop/rchain/casper/util/rholang/RuntimeManager.scala
  casper/src/test/scala/coop/rchain/casper/util/rholang/RuntimeSpec.scala
  node/src/test/scala/coop/rchain/node/mergeablity/MergeabilityRules.scala
  rspace/src/main/scala/coop/rchain/rspace/RSpace.scala
  rspace/src/main/scala/coop/rchain/rspace/channelStore/ChannelStore.scala
  rspace/src/main/scala/coop/rchain/rspace/channelStore/instances/ChannelStoreImpl.scala
  rspace/src/main/scala/coop/rchain/rspace/channelStore/syntax/ChannelStoreSyntax.scala
  rspace/src/main/scala/coop/rchain/rspace/hashing/Blake2b256Hash.scala
  rspace/src/main/scala/coop/rchain/rspace/hashing/ChannelHash.scala
  rspace/src/main/scala/coop/rchain/rspace/hashing/StableHashProvider.scala
  rspace/src/main/scala/coop/rchain/rspace/history/HistoryInstances.scala
  rspace/src/main/scala/coop/rchain/rspace/history/HistoryRepository.scala
  rspace/src/main/scala/coop/rchain/rspace/history/HistoryRepositoryImpl.scala
  rspace/src/main/scala/coop/rchain/rspace/history/instances/RSpaceHistoryReaderImpl.scala
  rspace/src/main/scala/coop/rchain/rspace/history/syntax/HistoryReaderSyntax.scala
  rspace/src/main/scala/coop/rchain/rspace/merger/MergingLogic.scala
  rspace/src/main/scala/coop/rchain/rspace/merger/StateChange.scala
  rspace/src/main/scala/coop/rchain/rspace/merger/StateChangeMerger.scala
  rspace/src/main/scala/coop/rchain/rspace/package.scala
  rspace/src/main/scala/coop/rchain/rspace/store/RSpaceStoreManagerSyntax.scala
  rspace/src/main/scala/coop/rchain/rspace/trace/Event.scala
  rspace/src/test/scala/coop/rchain/rspace/ReplayRSpaceTests.scala
  rspace/src/test/scala/coop/rchain/rspace/StorageTestsBase.scala
  rspace/src/test/scala/coop/rchain/rspace/history/HistoryRepositoryGenerativeSpec.scala
  rspace/src/test/scala/coop/rchain/rspace/history/HistoryRepositorySpec.scala
  rspace/src/test/scala/coop/rchain/rspace/history/HistorySpec.scala
  rspace/src/test/scala/coop/rchain/rspace/trace/EventTests.scala
Labels: feature-branch

#3478 Final snapshot on block 908300
  wallets_REV_BLOCK-908300.txt
Labels: documentation

#3480 Correction of wrong REV balance format in wallets.txt file
  wallets_REV_BLOCK-908300.txt
Labels: bug-fix

#3481 Make updating fork choice tips memory efficient
  casper/src/main/scala/coop/rchain/casper/engine/Running.scala
Labels: enhancement

#3482 Update wallets.txt file for Hard Fork 1
  wallets.txt
Labels: documentation

#3486 Fix LFS tests and use dequeue with one element in LFS requesters
  .github/workflows/continuous-integration.yml
  casper/src/main/scala/coop/rchain/casper/engine/LfsBlockRequester.scala
  casper/src/main/scala/coop/rchain/casper/engine/LfsTupleSpaceRequester.scala
  casper/src/test/scala/coop/rchain/casper/engine/LfsBlockRequesterEffectsSpec.scala
  casper/src/test/scala/coop/rchain/casper/engine/LfsStateRequesterEffectsSpec.scala
Labels: bug-fix, build-tests-ci

#3439 Per block dag view
  block-storage/src/main/scala/coop/rchain/blockstorage/dag/BlockDagKeyValueStorage.scala
  block-storage/src/main/scala/coop/rchain/blockstorage/dag/BlockDagRepresentationSyntax.scala
  block-storage/src/main/scala/coop/rchain/blockstorage/dag/BlockDagStorage.scala
  block-storage/src/test/scala/coop/rchain/blockstorage/dag/BlockDagKeyValueStorageTest.scala
  casper/src/main/scala/coop/rchain/casper/BlockDagRepresentationSyntax.scala
  casper/src/main/scala/coop/rchain/casper/Casper.scala
  casper/src/main/scala/coop/rchain/casper/MultiParentCasperImpl.scala
  casper/src/main/scala/coop/rchain/casper/blocks/BlockProcessor.scala
  casper/src/main/scala/coop/rchain/casper/blocks/proposer/Proposer.scala
  casper/src/main/scala/coop/rchain/casper/finality/Finalizer.scala
  casper/src/main/scala/coop/rchain/casper/merging/DagMerger.scala
  casper/src/main/scala/coop/rchain/casper/package.scala
  casper/src/main/scala/coop/rchain/casper/safety/CliqueOracle.scala
  casper/src/test/scala/coop/rchain/casper/addblock/MultiParentCasperAddBlockSpec.scala
  casper/src/test/scala/coop/rchain/casper/batch2/SingleParentCasperSpec.scala
  casper/src/test/scala/coop/rchain/casper/batch2/ValidateTest.scala
  casper/src/test/scala/coop/rchain/casper/genesis/GenesisTest.scala
  casper/src/test/scala/coop/rchain/casper/helper/BlockGenerator.scala
  casper/src/test/scala/coop/rchain/casper/helper/NoOpsCasperEffect.scala
  casper/src/test/scala/coop/rchain/casper/helper/TestNode.scala
  casper/src/test/scala/coop/rchain/casper/util/rholang/InterpreterUtilTest.scala
  casper/src/test/scala/coop/rchain/casper/util/rholang/Resources.scala
  node/src/test/scala/coop/rchain/node/mergeablity/MergingBranchMergerSpec.scala
Labels: enhancement, feature-branch

#3489 Fix LFS block requester for duplicate requests created
  casper/src/main/scala/coop/rchain/casper/engine/LfsBlockRequester.scala
  casper/src/test/scala/coop/rchain/casper/engine/LfsBlockRequesterStateSpec.scala
Labels: bug-fix

#3484 Require latest messages justifications for LFS
  casper/src/main/scala/coop/rchain/casper/engine/BlockRetriever.scala
  casper/src/main/scala/coop/rchain/casper/engine/Initializing.scala
  casper/src/main/scala/coop/rchain/casper/engine/LfsBlockRequester.scala
Labels: bug-fix

#3494 Duplicate block processing fix
  casper/src/main/scala/coop/rchain/casper/engine/Running.scala
Labels: bug-fix
