Repository rchain/rchain, pull requests merged in 2021-11, with the labels that each got.

#3521 Use DAG to find BlockMessage by truncated hash string to increase performance
  block-storage/src/main/scala/coop/rchain/blockstorage/BlockStore.scala
  block-storage/src/main/scala/coop/rchain/blockstorage/KeyValueBlockStore.scala
  block-storage/src/main/scala/coop/rchain/blockstorage/dag/BlockDagKeyValueStorage.scala
  block-storage/src/main/scala/coop/rchain/blockstorage/dag/BlockDagStorage.scala
  block-storage/src/test/scala/coop/rchain/blockstorage/KeyValueBlockStoreSpec.scala
  casper/src/main/scala/coop/rchain/casper/api/BlockAPI.scala
  casper/src/test/scala/coop/rchain/casper/util/rholang/Resources.scala
Labels: enhancement

#3529 Fixed method to find BlockHash by truncated string with odd length
  block-storage/src/main/scala/coop/rchain/blockstorage/dag/BlockDagKeyValueStorage.scala
Labels: bug-fix

#3531 Unwraps bundle body in WebAPI implementation
  node/src/main/scala/coop/rchain/node/api/WebApi.scala
Labels: bug-fix

#3525 Use only unique changes for merging random generators
  rholang/src/main/scala/coop/rchain/rholang/interpreter/merging/RholangMergingLogic.scala
Labels: feature-branch

#3535 History::reset method and related HistoryRepository::getHistoryReaded method are wrapped into F
  casper/src/main/scala/coop/rchain/casper/merging/BlockIndex.scala
  casper/src/main/scala/coop/rchain/casper/merging/DagMerger.scala
  casper/src/main/scala/coop/rchain/casper/merging/DeployChainIndex.scala
  rspace/src/main/scala/coop/rchain/rspace/RSpace.scala
  rspace/src/main/scala/coop/rchain/rspace/RSpaceOps.scala
  rspace/src/main/scala/coop/rchain/rspace/ReplayRSpace.scala
  rspace/src/main/scala/coop/rchain/rspace/history/History.scala
  rspace/src/main/scala/coop/rchain/rspace/history/HistoryInstances.scala
  rspace/src/main/scala/coop/rchain/rspace/history/HistoryRepository.scala
  rspace/src/main/scala/coop/rchain/rspace/history/HistoryRepositoryImpl.scala
  rspace/src/test/scala/coop/rchain/rspace/ReplayRSpaceTests.scala
  rspace/src/test/scala/coop/rchain/rspace/StorageTestsBase.scala
  rspace/src/test/scala/coop/rchain/rspace/history/HistoryRepositoryGenerativeSpec.scala
  rspace/src/test/scala/coop/rchain/rspace/history/HistoryRepositorySpec.scala
  rspace/src/test/scala/coop/rchain/rspace/history/SimplisticHistory.scala
Labels: enhancement
