Repository rchain/rchain, pull requests merged in 2021-05, with the labels that each got.

#3395 Add to log duration of block creation and replay
  casper/src/main/scala/coop/rchain/casper/MultiParentCasperImpl.scala
  casper/src/main/scala/coop/rchain/casper/blocks/proposer/BlockCreator.scala
  shared/src/main/scala/coop/rchain/shared/Stopwatch.scala
Labels: enhancement

#3398 Fix "tut" sbt plugin outaged problem
  build.sbt
  project/plugins.sbt
Labels: bug-fix, build-tests-ci

#3400 Print approved block when node starts
  casper/src/main/scala/coop/rchain/casper/engine/Engine.scala
Labels: diagnostics

#3405 Print user deploy errors to log (play/replay/reporting)
  casper/src/main/scala/coop/rchain/casper/MultiParentCasperImpl.scala
  casper/src/main/scala/coop/rchain/casper/blocks/proposer/BlockCreator.scala
  casper/src/main/scala/coop/rchain/casper/util/rholang/CasperRhoRuntimeSyntax.scala
  casper/src/main/scala/coop/rchain/casper/util/rholang/InterpreterUtil.scala
Labels: diagnostics

#3416 added missing List.toSet() documentation
  rholang/reference_doc/data_structures/README.md
Labels: documentation

#3410 Per deploy merge
  casper/src/main/scala/coop/rchain/casper/MultiParentCasperImpl.scala
  casper/src/main/scala/coop/rchain/casper/blocks/merger/CasperDagMerger.scala
  casper/src/main/scala/coop/rchain/casper/blocks/merger/Indexer.scala
  casper/src/main/scala/coop/rchain/casper/blocks/proposer/BlockCreator.scala
  casper/src/main/scala/coop/rchain/casper/merging/BlockIndex.scala
  casper/src/main/scala/coop/rchain/casper/merging/ConflictSetMerger.scala
  casper/src/main/scala/coop/rchain/casper/merging/DagMerger.scala
  casper/src/main/scala/coop/rchain/casper/merging/DeployChainIndex.scala
  casper/src/main/scala/coop/rchain/casper/merging/DeployIndex.scala
  casper/src/main/scala/coop/rchain/casper/util/rholang/InterpreterUtil.scala
  casper/src/main/scala/coop/rchain/casper/util/rholang/RuntimeManager.scala
  casper/src/test/scala/coop/rchain/casper/batch1/MergeabilityRules.scala
  casper/src/test/scala/coop/rchain/casper/batch1/MultiParentCasperCommunicationSpec.scala
  casper/src/test/scala/coop/rchain/casper/batch1/MultiParentCasperMergeSpec.scala
  casper/src/test/scala/coop/rchain/casper/batch1/StateMergerSpec.scala
  casper/src/test/scala/coop/rchain/casper/helper/TestNode.scala
  casper/src/test/scala/coop/rchain/casper/util/GenesisBuilder.scala
  casper/src/test/scala/coop/rchain/casper/util/rholang/InterpreterUtilTest.scala
  casper/src/test/scala/coop/rchain/casper/util/rholang/MergingBranchMergerSpec.scala
  rspace/src/main/scala/coop/rchain/rspace/HotStoreTrieAction.scala
  rspace/src/main/scala/coop/rchain/rspace/channelStore/syntax/ChannelStoreSyntax.scala
  rspace/src/main/scala/coop/rchain/rspace/history/HistoryRepository.scala
  rspace/src/main/scala/coop/rchain/rspace/history/HistoryRepositoryImpl.scala
  rspace/src/main/scala/coop/rchain/rspace/merger/ChannelChange.scala
  rspace/src/main/scala/coop/rchain/rspace/merger/EvenLogIndex.scala
  rspace/src/main/scala/coop/rchain/rspace/merger/EventLogIndex.scala
  rspace/src/main/scala/coop/rchain/rspace/merger/MergingLogic.scala
  rspace/src/main/scala/coop/rchain/rspace/merger/StateChange.scala
  rspace/src/main/scala/coop/rchain/rspace/merger/StateChangeMerger.scala
  rspace/src/main/scala/coop/rchain/rspace/merger/StateMerger.scala
  rspace/src/main/scala/coop/rchain/rspace/merger/instances/DiffStateMerger.scala
  rspace/src/main/scala/coop/rchain/rspace/merger/instances/EventLogIndexConflictDetector.scala
  rspace/src/main/scala/coop/rchain/rspace/merger/package.scala
  rspace/src/main/scala/coop/rchain/rspace/serializers/ScodecSerialize.scala
  shared/src/main/scala/coop/rchain/shared/Stopwatch.scala
Labels: enhancement, feature-branch
