Repository rchain/rchain, pull requests merged in 2021-04, with the labels that each got.

#3365 Merge dev into block-merge
  .github/workflows/continuous-integration.yml
  DEVELOPER.md
  block-storage/src/main/scala/coop/rchain/blockstorage/FileLMDBIndexBlockStore.scala
  block-storage/src/main/scala/coop/rchain/blockstorage/dag/BlockDagFileStorage.scala
  block-storage/src/main/scala/coop/rchain/blockstorage/dag/BlockDagKeyValueStorage.scala
  block-storage/src/main/scala/coop/rchain/blockstorage/dag/BlockDagStorage.scala
  block-storage/src/main/scala/coop/rchain/blockstorage/dag/BlockMetadataPersistentIndex.scala
  block-storage/src/main/scala/coop/rchain/blockstorage/dag/DeployPersistentIndex.scala
  block-storage/src/main/scala/coop/rchain/blockstorage/dag/EquivocationTrackerPersistentIndex.scala
  block-storage/src/main/scala/coop/rchain/blockstorage/dag/InMemBlockDagStorage.scala
  block-storage/src/main/scala/coop/rchain/blockstorage/dag/InvalidBlocksPersistentIndex.scala
  block-storage/src/main/scala/coop/rchain/blockstorage/dag/LatestMessagesPersistentIndex.scala
  block-storage/src/main/scala/coop/rchain/blockstorage/dag/PersistentIndex.scala
  block-storage/src/main/scala/coop/rchain/blockstorage/errors.scala
  block-storage/src/main/scala/coop/rchain/blockstorage/finality/LastFinalizedFileStorage.scala
  block-storage/src/main/scala/coop/rchain/blockstorage/finality/LastFinalizedKeyValueStorage.scala
  block-storage/src/test/scala/coop/rchain/blockstorage/dag/BlockDagKeyValueStorageTest.scala
  block-storage/src/test/scala/coop/rchain/blockstorage/dag/BlockDagStorageTest.scala
  block-storage/src/test/scala/coop/rchain/blockstorage/dag/IndexedBlockDagStorage.scala
  block-storage/src/test/scala/coop/rchain/blockstorage/finality/LastFinalizedFileStorageTest.scala
  build.sbt
  casper/src/main/scala/coop/rchain/casper/CasperConf.scala
  casper/src/main/scala/coop/rchain/casper/engine/ApproveBlockProtocol.scala
  casper/src/main/scala/coop/rchain/casper/engine/BlockApproverProtocol.scala
  casper/src/main/scala/coop/rchain/casper/engine/CasperLaunch.scala
  casper/src/main/scala/coop/rchain/casper/util/BondsParser.scala
  casper/src/main/scala/coop/rchain/casper/util/VaultParser.scala
  casper/src/test/scala/coop/rchain/casper/engine/BlockApproverProtocolTest.scala
  casper/src/test/scala/coop/rchain/casper/engine/Setup.scala
  casper/src/test/scala/coop/rchain/casper/genesis/GenesisTest.scala
  casper/src/test/scala/coop/rchain/casper/helper/TestNode.scala
  casper/src/test/scala/coop/rchain/casper/util/rholang/Resources.scala
  nix/README.md
  node/src/main/scala/coop/rchain/node/BlockStoreMigrate.scala
  node/src/main/scala/coop/rchain/node/Main.scala
  node/src/main/scala/coop/rchain/node/runtime/NodeRuntime.scala
  node/src/main/scala/coop/rchain/node/runtime/Setup.scala
  node/src/test/scala/coop/rchain/node/configuration/commandline/ConfigMapperSpec.scala
  node/src/test/scala/coop/rchain/node/configuration/hocon/HoconConfigurationSpec.scala
  rspace/src/main/scala/coop/rchain/rspace/RSpaceOps.scala
  rspace/src/main/scala/coop/rchain/rspace/concurrent/MultiLock.scala
  rspace/src/main/scala/coop/rchain/rspace/concurrent/TwoStepLock.scala
Labels: feature-branch

#3367 Disable channels map for single parent
  casper/src/main/scala/coop/rchain/casper/storage/RNodeKeyValueStoreManager.scala
  node/src/main/scala/coop/rchain/node/runtime/Setup.scala
  rholang/src/main/scala/coop/rchain/rholang/interpreter/RholangCLI.scala
  rspace/src/main/scala/coop/rchain/rspace/channelStore/instances/ChannelStoreImpl.scala
  rspace/src/main/scala/coop/rchain/rspace/store/RSpaceStoreManagerSyntax.scala
  shared/src/main/scala/coop/rchain/store/NoOpKeyValueStore.scala
Labels: enhancement

#3374 Fix sync call to propose
  casper/src/main/scala/coop/rchain/casper/api/BlockAPI.scala
  casper/src/main/scala/coop/rchain/casper/blocks/proposer/Proposer.scala
  casper/src/main/scala/coop/rchain/casper/package.scala
  node/src/main/scala/coop/rchain/node/api/WebApi.scala
  node/src/main/scala/coop/rchain/node/instances/ProposerInstance.scala
  node/src/main/scala/coop/rchain/node/runtime/NodeRuntime.scala
  node/src/main/scala/coop/rchain/node/runtime/Setup.scala
Labels: bug-fix

#3377 Disable block index caching on single parent
  casper/src/main/scala/coop/rchain/casper/MultiParentCasperImpl.scala
Labels: enhancement, feature-branch
