Repository rchain/rchain, pull requests merged in 2021-03, with the labels that each got.

#3341 Fix CI release with latest tag
  .github/workflows/continuous-integration.yml
Labels: build-tests-ci

#3338 Fix generation of bonds and wallets file
  casper/src/main/scala/coop/rchain/casper/CasperConf.scala
  casper/src/main/scala/coop/rchain/casper/engine/ApproveBlockProtocol.scala
  casper/src/main/scala/coop/rchain/casper/engine/CasperLaunch.scala
  casper/src/main/scala/coop/rchain/casper/util/BondsParser.scala
  casper/src/main/scala/coop/rchain/casper/util/VaultParser.scala
  casper/src/test/scala/coop/rchain/casper/genesis/GenesisTest.scala
  node/src/test/scala/coop/rchain/node/configuration/commandline/ConfigMapperSpec.scala
  node/src/test/scala/coop/rchain/node/configuration/hocon/HoconConfigurationSpec.scala
Labels: bug-fix

#3352 propose enables sync version by default and adds async version as an option
  casper/src/main/scala/coop/rchain/casper/api/BlockAPI.scala
  casper/src/main/scala/coop/rchain/casper/blocks/proposer/Proposer.scala
  casper/src/main/scala/coop/rchain/casper/package.scala
  casper/src/main/scala/coop/rchain/casper/util/comm/ProposeService.scala
  integration-tests/Pipfile
  integration-tests/Pipfile.lock
  integration-tests/test/rnode.py
  integration-tests/test/test_bonding_validators.py
  integration-tests/test/test_synchrony_constraint.py
  integration-tests/test/test_unbond.py
  models/src/main/protobuf/ProposeServiceCommon.proto
  models/src/main/protobuf/ProposeServiceV1.proto
  node/src/main/scala/coop/rchain/node/api/ProposeGrpcServiceV1.scala
  node/src/main/scala/coop/rchain/node/api/WebApi.scala
  node/src/main/scala/coop/rchain/node/instances/BlockProcessorInstance.scala
  node/src/main/scala/coop/rchain/node/instances/ProposerInstance.scala
  node/src/main/scala/coop/rchain/node/runtime/NodeRuntime.scala
  node/src/main/scala/coop/rchain/node/runtime/Setup.scala
Labels: feature-branch

#3304 Update block message field with rejectedDeploys
  casper/src/main/scala/coop/rchain/casper/BlockStatus.scala
  casper/src/main/scala/coop/rchain/casper/api/BlockAPI.scala
  casper/src/main/scala/coop/rchain/casper/blocks/proposer/BlockCreator.scala
  casper/src/main/scala/coop/rchain/casper/genesis/Genesis.scala
  casper/src/main/scala/coop/rchain/casper/util/rholang/InterpreterUtil.scala
  casper/src/test/scala/coop/rchain/casper/addblock/MultiParentCasperAddBlockSpec.scala
  casper/src/test/scala/coop/rchain/casper/helper/BlockGenerator.scala
  casper/src/test/scala/coop/rchain/casper/util/rholang/InterpreterUtilTest.scala
  models/src/main/protobuf/CasperMessage.proto
  models/src/main/protobuf/DeployServiceCommon.proto
  models/src/main/scala/coop/rchain/casper/protocol/CasperMessage.scala
  models/src/test/scala/coop/rchain/models/blockImplicits.scala
  node/src/main/scala/coop/rchain/node/web/WebApiRoutes.scala
  node/src/test/scala/coop/rchain/node/web/WebApiRoutesTest.scala
Labels: feature-branch

#3358 Propose on start
  casper/src/main/scala/coop/rchain/casper/engine/CasperLaunch.scala
  node/src/main/scala/coop/rchain/node/runtime/Setup.scala
Labels: enhancement, feature-branch

#3348 Update build.sbt with fixed Java version
  DEVELOPER.md
  build.sbt
  nix/README.md
Labels: build-tests-ci

#3359 Remove caching from RSpace
  casper/src/main/scala/coop/rchain/casper/storage/RNodeKeyValueStoreManager.scala
  rspace/src/main/scala/coop/rchain/rspace/InMemRSpaceCache.scala
  rspace/src/main/scala/coop/rchain/rspace/RSpace.scala
  rspace/src/main/scala/coop/rchain/rspace/history/HistoryRepository.scala
  rspace/src/main/scala/coop/rchain/rspace/history/HistoryRepositoryImpl.scala
  rspace/src/main/scala/coop/rchain/rspace/history/instances/CachingHashHistoryReaderImpl.scala
  rspace/src/test/scala/coop/rchain/rspace/ReplayRSpaceTests.scala
  rspace/src/test/scala/coop/rchain/rspace/StorageTestsBase.scala
  rspace/src/test/scala/coop/rchain/rspace/history/HistoryRepositoryGenerativeSpec.scala
  rspace/src/test/scala/coop/rchain/rspace/history/HistoryRepositorySpec.scala
Labels: enhancement

#3353 Fix memory leak in RSpace
  rspace/src/main/scala/coop/rchain/rspace/RSpaceOps.scala
  rspace/src/main/scala/coop/rchain/rspace/concurrent/MultiLock.scala
  rspace/src/main/scala/coop/rchain/rspace/concurrent/TwoStepLock.scala
Labels: bug-fix

#3361 Validate content of genesis block against local config
  casper/src/main/scala/coop/rchain/casper/engine/BlockApproverProtocol.scala
  casper/src/test/scala/coop/rchain/casper/engine/BlockApproverProtocolTest.scala
  casper/src/test/scala/coop/rchain/casper/engine/Setup.scala
Labels: bug

#3363 Remove legacy file based block dag store
  block-storage/src/main/scala/coop/rchain/blockstorage/dag/BlockDagFileStorage.scala
  block-storage/src/main/scala/coop/rchain/blockstorage/dag/BlockDagKeyValueStorage.scala
  block-storage/src/main/scala/coop/rchain/blockstorage/dag/BlockDagStorage.scala
  block-storage/src/main/scala/coop/rchain/blockstorage/dag/BlockMetadataPersistentIndex.scala
  block-storage/src/main/scala/coop/rchain/blockstorage/dag/DeployPersistentIndex.scala
  block-storage/src/main/scala/coop/rchain/blockstorage/dag/EquivocationTrackerPersistentIndex.scala
  block-storage/src/main/scala/coop/rchain/blockstorage/dag/InMemBlockDagStorage.scala
  block-storage/src/main/scala/coop/rchain/blockstorage/dag/InvalidBlocksPersistentIndex.scala
  block-storage/src/main/scala/coop/rchain/blockstorage/dag/LatestMessagesPersistentIndex.scala
  block-storage/src/main/scala/coop/rchain/blockstorage/dag/PersistentIndex.scala
  block-storage/src/main/scala/coop/rchain/blockstorage/errors.scala
  block-storage/src/main/scala/coop/rchain/blockstorage/finality/LastFinalizedFileStorage.scala
  block-storage/src/main/scala/coop/rchain/blockstorage/finality/LastFinalizedKeyValueStorage.scala
  block-storage/src/test/scala/coop/rchain/blockstorage/dag/BlockDagKeyValueStorageTest.scala
  block-storage/src/test/scala/coop/rchain/blockstorage/dag/BlockDagStorageTest.scala
  block-storage/src/test/scala/coop/rchain/blockstorage/dag/IndexedBlockDagStorage.scala
  block-storage/src/test/scala/coop/rchain/blockstorage/finality/LastFinalizedFileStorageTest.scala
  node/src/main/scala/coop/rchain/node/NodeRuntime.scala
Labels: enhancement
