Repository rchain/rchain, pull requests merged in 2021-08, with the labels that each got.

#3433 Add transaction api
  build.sbt
  casper/src/main/scala/coop/rchain/casper/api/BlockReportAPI.scala
  casper/src/main/scala/coop/rchain/casper/storage/RNodeKeyValueStoreManager.scala
  node/src/main/scala/coop/rchain/node/api/DeployGrpcServiceV1.scala
  node/src/main/scala/coop/rchain/node/api/WebApi.scala
  node/src/main/scala/coop/rchain/node/encode/JsonEncoder.scala
  node/src/main/scala/coop/rchain/node/runtime/Setup.scala
  node/src/main/scala/coop/rchain/node/web/ReportingRoutes.scala
  node/src/main/scala/coop/rchain/node/web/Transaction.scala
  node/src/main/scala/coop/rchain/node/web/WebApiRoutes.scala
  node/src/test/scala/coop/rchain/node/TransactionAPISpec.scala
  node/src/test/scala/coop/rchain/node/web/WebApiRoutesTest.scala
  rspace/src/main/scala/coop/rchain/rspace/hashing/Blake2b256Hash.scala
Labels: enhancement

#3497 Fix history trie encoding problem
  casper/src/main/scala/coop/rchain/casper/engine/Initializing.scala
  casper/src/main/scala/coop/rchain/casper/util/rholang/RuntimeManager.scala
  casper/src/test/scala/coop/rchain/casper/util/rholang/RuntimeSpec.scala
  rspace/src/main/scala/coop/rchain/rspace/history/History.scala
  rspace/src/main/scala/coop/rchain/rspace/history/HistoryRepositoryImpl.scala
  rspace/src/main/scala/coop/rchain/rspace/serializers/ScodecSerialize.scala
  rspace/src/main/scala/coop/rchain/rspace/state/RSpaceExporterSyntax.scala
  rspace/src/main/scala/coop/rchain/rspace/state/RSpaceImporter.scala
  rspace/src/main/scala/coop/rchain/rspace/state/exporters/RSpaceExporterDisk.scala
Labels: bug-fix

#3505 Mark branches with duplicated deploys as conflicting
  casper/src/main/scala/coop/rchain/casper/merging/BlockIndex.scala
  casper/src/main/scala/coop/rchain/casper/merging/DagMerger.scala
  casper/src/main/scala/coop/rchain/casper/merging/DeployIndex.scala
Labels: enhancement

#3370 Fix score for binary data, different ByteString should not be equal
  casper/src/test/resources/PoSTest.rho
  models/src/main/scala/coop/rchain/models/rholang/sorter/ExprSortMatcher.scala
  models/src/test/scala/coop/rchain/models/rholang/SortTest.scala
Labels: feature-branch, need-hard-fork

#3503 Rejection options compute bug fix + tests
  casper/src/main/scala/coop/rchain/casper/merging/DeployChainIndex.scala
  casper/src/main/scala/coop/rchain/casper/util/ConstructDeploy.scala
  casper/src/test/scala/coop/rchain/casper/merging/MerginBenchmark.scala
  rspace/src/main/scala/coop/rchain/rspace/merger/MergingLogic.scala
  rspace/src/test/scala/coop/rchain/rspace/merging/MergingLogicSpec.scala
Labels: bug-fix
