Repository rchain/rchain, pull requests merged in 2022-03, with the labels that each got.

#3612 Web API v1 (with OpenAPI schema)
  casper/src/main/scala/coop/rchain/casper/ReportingProtoTransformer.scala
  casper/src/main/scala/coop/rchain/casper/api/BlockAPI.scala
  casper/src/main/scala/coop/rchain/casper/api/BlockReportAPI.scala
  casper/src/main/scala/coop/rchain/casper/util/comm/DeployRuntime.scala
  casper/src/test/scala/coop/rchain/casper/api/BlockQueryResponseAPITest.scala
  casper/src/test/scala/coop/rchain/casper/api/ListeningNameAPITest.scala
  models/src/main/protobuf/CasperMessage.proto
  models/src/main/protobuf/DeployServiceCommon.proto
  models/src/main/protobuf/DeployServiceV1.proto
  models/src/main/scala/coop/rchain/casper/protocol/CasperMessage.scala
  node/src/main/scala/coop/rchain/node/api/DeployGrpcServiceV1.scala
  node/src/main/scala/coop/rchain/node/api/WebApi.scala
  node/src/main/scala/coop/rchain/node/api/json/JsonEntitiesCirceFromSchema.scala
  node/src/main/scala/coop/rchain/node/api/json/JsonSchemaDerivation.scala
  node/src/main/scala/coop/rchain/node/api/v1/WebApiAdminEndpoints.scala
  node/src/main/scala/coop/rchain/node/api/v1/WebApiEndpoints.scala
  node/src/main/scala/coop/rchain/node/encode/JsonEncoder.scala
  node/src/main/scala/coop/rchain/node/runtime/ServersInstances.scala
  node/src/main/scala/coop/rchain/node/web/Transaction.scala
  node/src/main/scala/coop/rchain/node/web/WebApiDocsV1.scala
  node/src/main/scala/coop/rchain/node/web/WebApiRoutesV1.scala
  node/src/main/scala/coop/rchain/node/web/https4s/RouterFix.scala
  node/src/main/scala/coop/rchain/node/web/package.scala
  project/Dependencies.scala
Labels: enhancement, API

#3559 Create PoS vault based on unforgeable name (PoS contract)
  casper/src/main/resources/PoS.rhox
  casper/src/main/scala/coop/rchain/casper/rholang/RuntimeSyntax.scala
  casper/src/test/resources/PoSTest.rho
  casper/src/test/scala/coop/rchain/casper/util/GenesisBuilder.scala
  integration-tests/test/test_bonding_validators.py
  integration-tests/test/test_unbond.py
  integration-tests/test/test_wallets.py
Labels: enhancement, feature-branch, rholang

#3591 New reject rule for overflow and negative merged results
  casper/src/main/scala/coop/rchain/casper/merging/ConflictSetMerger.scala
  casper/src/main/scala/coop/rchain/casper/merging/DagMerger.scala
  casper/src/test/scala/coop/rchain/casper/merging/MergeNumberChannelSpec.scala
Labels: enhancement, feature-branch

#3568 Radix history (scala implementation)
  casper/src/main/scala/coop/rchain/casper/util/rholang/RuntimeManager.scala
  casper/src/test/scala/coop/rchain/casper/util/rholang/RuntimeSpec.scala
  node/src/test/scala/coop/rchain/node/perf/HistoryGenKeySpec.scala
  rspace/src/it/scala/coop/rchain/rspace/history/MergingHistoryGenerativeSpec.scala
  rspace/src/main/scala/coop/rchain/rspace/history/History.scala
  rspace/src/main/scala/coop/rchain/rspace/history/HistoryMergingInstances.scala
  rspace/src/main/scala/coop/rchain/rspace/history/HistoryRepository.scala
  rspace/src/main/scala/coop/rchain/rspace/history/RadixTree.scala
  rspace/src/main/scala/coop/rchain/rspace/history/instances/RadixHistory.scala
  rspace/src/main/scala/coop/rchain/rspace/state/RSpaceExporter.scala
  rspace/src/main/scala/coop/rchain/rspace/state/RSpaceImporter.scala
  rspace/src/main/scala/coop/rchain/rspace/state/instances/RSpaceExporterStore.scala
  rspace/src/test/scala/coop/rchain/rspace/ExportImportTests.scala
  rspace/src/test/scala/coop/rchain/rspace/history/HistoryActionTests.scala
  rspace/src/test/scala/coop/rchain/rspace/history/HistoryRepositoryGenerativeSpec.scala
  rspace/src/test/scala/coop/rchain/rspace/history/HistoryRepositorySpec.scala
  rspace/src/test/scala/coop/rchain/rspace/history/MergingCachingHistorySpec.scala
  rspace/src/test/scala/coop/rchain/rspace/history/MergingHistorySpec.scala
  rspace/src/test/scala/coop/rchain/rspace/history/SimplisticHistory.scala
  shared/src/main/scala/coop/rchain/shared/Stopwatch.scala
  shared/src/main/scala/coop/rchain/store/InMemoryKeyValueStore.scala
Labels: enhancement, feature-branch

#3577 Use unforgeable name as mergeable channel tag
  casper/src/main/resources/NonNegativeNumber.rho
  casper/src/main/scala/coop/rchain/casper/ReportingCasper.scala
  casper/src/main/scala/coop/rchain/casper/genesis/Genesis.scala
  casper/src/main/scala/coop/rchain/casper/util/rholang/RuntimeManager.scala
  casper/src/test/scala/coop/rchain/casper/batch2/ValidateTest.scala
  casper/src/test/scala/coop/rchain/casper/engine/Setup.scala
  casper/src/test/scala/coop/rchain/casper/genesis/GenesisTest.scala
  casper/src/test/scala/coop/rchain/casper/helper/RhoSpec.scala
  casper/src/test/scala/coop/rchain/casper/helper/TestNode.scala
  casper/src/test/scala/coop/rchain/casper/merging/MergeNumberChannelSpec.scala
  casper/src/test/scala/coop/rchain/casper/util/GenesisBuilder.scala
  casper/src/test/scala/coop/rchain/casper/util/rholang/Interactive.scala
  casper/src/test/scala/coop/rchain/casper/util/rholang/Resources.scala
  casper/src/test/scala/coop/rchain/casper/util/rholang/RuntimeManagerTest.scala
  casper/src/test/scala/coop/rchain/casper/util/rholang/RuntimeSpec.scala
  node/src/main/scala/coop/rchain/node/revvaultexport/StateBalances.scala
  node/src/main/scala/coop/rchain/node/revvaultexport/mainnet1/StateBalanceMain.scala
  node/src/main/scala/coop/rchain/node/revvaultexport/mainnet1/reporting/MergeBalanceMain.scala
  node/src/main/scala/coop/rchain/node/revvaultexport/reporting/TransactionBalances.scala
  node/src/main/scala/coop/rchain/node/runtime/Setup.scala
  rholang/src/main/scala/coop/rchain/rholang/interpreter/Reduce.scala
  rholang/src/main/scala/coop/rchain/rholang/interpreter/RhoRuntime.scala
  rholang/src/main/scala/coop/rchain/rholang/interpreter/RholangCLI.scala
  rholang/src/main/scala/coop/rchain/rholang/interpreter/dispatch.scala
  rholang/src/test/scala/coop/rchain/rholang/Resources.scala
  rholang/src/test/scala/coop/rchain/rholang/interpreter/CostAccountingReducerTest.scala
  rholang/src/test/scala/coop/rchain/rholang/interpreter/RholangOnlyDispatcher.scala
  rholang/src/test/scala/coop/rchain/rholang/interpreter/accounting/CostAccountingSpec.scala
Labels: enhancement, feature-branch, rholang

#3620 Sync dev with feature/radix-history
  casper/src/main/scala/coop/rchain/casper/util/rholang/RuntimeManager.scala
  casper/src/test/scala/coop/rchain/casper/util/rholang/RuntimeSpec.scala
  node/src/test/scala/coop/rchain/node/perf/HistoryGenKeySpec.scala
  rspace/src/it/scala/coop/rchain/rspace/history/MergingHistoryGenerativeSpec.scala
  rspace/src/main/scala/coop/rchain/rspace/history/History.scala
  rspace/src/main/scala/coop/rchain/rspace/history/HistoryMergingInstances.scala
  rspace/src/main/scala/coop/rchain/rspace/history/HistoryRepository.scala
  rspace/src/main/scala/coop/rchain/rspace/history/RadixTree.scala
  rspace/src/main/scala/coop/rchain/rspace/history/instances/RadixHistory.scala
  rspace/src/main/scala/coop/rchain/rspace/state/RSpaceExporter.scala
  rspace/src/main/scala/coop/rchain/rspace/state/RSpaceImporter.scala
  rspace/src/main/scala/coop/rchain/rspace/state/instances/RSpaceExporterStore.scala
  rspace/src/test/scala/coop/rchain/rspace/ExportImportTests.scala
  rspace/src/test/scala/coop/rchain/rspace/history/HistoryActionTests.scala
  rspace/src/test/scala/coop/rchain/rspace/history/HistoryRepositoryGenerativeSpec.scala
  rspace/src/test/scala/coop/rchain/rspace/history/HistoryRepositorySpec.scala
  rspace/src/test/scala/coop/rchain/rspace/history/MergingCachingHistorySpec.scala
  rspace/src/test/scala/coop/rchain/rspace/history/MergingHistorySpec.scala
  rspace/src/test/scala/coop/rchain/rspace/history/SimplisticHistory.scala
  shared/src/main/scala/coop/rchain/shared/Stopwatch.scala
  shared/src/main/scala/coop/rchain/store/InMemoryKeyValueStore.scala
Labels: next-release

#3630 SDK project with initial Dag Manager abstraction
  build.sbt
  casper/src/main/scala/coop/rchain/casper/engine/BlockRetriever.scala
  node/src/main/scala/coop/rchain/node/dag/RNodeStateSetup.scala
  node/src/main/scala/coop/rchain/node/dag/implementation/NetworkBlockRequester.scala
  node/src/main/scala/coop/rchain/node/dag/implementation/RNodeDagManager.scala
  rspace-bench/src/test/scala/coop/rchain/lmdb/Context.scala
  rspace-bench/src/test/scala/coop/rchain/lmdb/LMDBStore.scala
  sdk/src/main/scala/coop/rchain/sdk/block/BlockRequester.scala
  sdk/src/main/scala/coop/rchain/sdk/casper/syntax/CasperDagDataSyntax.scala
  sdk/src/main/scala/coop/rchain/sdk/casper/syntax/CasperDagViewSyntax.scala
  sdk/src/main/scala/coop/rchain/sdk/casper/syntax/package.scala
  sdk/src/main/scala/coop/rchain/sdk/dag/data/DagData.scala
  sdk/src/main/scala/coop/rchain/sdk/dag/data/DagManager.scala
  sdk/src/main/scala/coop/rchain/sdk/dag/data/DagView.scala
  sdk/src/main/scala/coop/rchain/sdk/dag/syntax/DagDataSyntax.scala
  sdk/src/main/scala/coop/rchain/sdk/dag/syntax/DagViewSyntax.scala
  sdk/src/main/scala/coop/rchain/sdk/dag/syntax/package.scala
  sdk/src/test/scala/coop/rchain/sdk/SdkSpec.scala
Labels: enhancement

#3629 Fix rholang treeHashMap `get`, `set` on the same key at the same time bug
  casper/src/main/resources/Registry.rho
  casper/src/test/resources/TreeHashMapTest.rho
Labels: bug-fix, rholang

#3639 Fix multi-sig vault with public key authentication
  casper/src/main/resources/MultiSigRevVault.rho
Labels: bug-fix, Priority-High

#3631 Add shard id to deploy data
  casper/src/main/scala/coop/rchain/casper/Validate.scala
  casper/src/main/scala/coop/rchain/casper/api/BlockAPI.scala
  casper/src/main/scala/coop/rchain/casper/blocks/proposer/BlockCreator.scala
  casper/src/main/scala/coop/rchain/casper/engine/BlockApproverProtocol.scala
  casper/src/main/scala/coop/rchain/casper/engine/GenesisValidator.scala
  casper/src/main/scala/coop/rchain/casper/genesis/Genesis.scala
  casper/src/main/scala/coop/rchain/casper/genesis/contracts/StandardDeploys.scala
  casper/src/main/scala/coop/rchain/casper/util/ConstructDeploy.scala
  casper/src/main/scala/coop/rchain/casper/util/comm/DeployRuntime.scala
  casper/src/test/scala/coop/rchain/casper/addblock/MultiParentCasperAddBlockSpec.scala
  casper/src/test/scala/coop/rchain/casper/api/BondedStatusAPITest.scala
  casper/src/test/scala/coop/rchain/casper/api/ExploratoryDeployAPITest.scala
  casper/src/test/scala/coop/rchain/casper/api/LastFinalizedAPITest.scala
  casper/src/test/scala/coop/rchain/casper/api/ListeningNameAPITest.scala
  casper/src/test/scala/coop/rchain/casper/batch1/MultiParentCasperCommunicationSpec.scala
  casper/src/test/scala/coop/rchain/casper/batch1/MultiParentCasperDeploySpec.scala
  casper/src/test/scala/coop/rchain/casper/batch1/MultiParentCasperFinalizationSpec.scala
  casper/src/test/scala/coop/rchain/casper/batch1/MultiParentCasperMergeSpec.scala
  casper/src/test/scala/coop/rchain/casper/batch1/MultiParentCasperReportingSpec.scala
  casper/src/test/scala/coop/rchain/casper/batch1/MultiParentCasperRholangSpec.scala
  casper/src/test/scala/coop/rchain/casper/batch1/MultiParentCasperSmokeSpec.scala
  casper/src/test/scala/coop/rchain/casper/batch2/RholangBuildTest.scala
  casper/src/test/scala/coop/rchain/casper/batch2/SingleParentCasperSpec.scala
  casper/src/test/scala/coop/rchain/casper/batch2/ValidateTest.scala
  casper/src/test/scala/coop/rchain/casper/engine/BlockApproverProtocolTest.scala
  casper/src/test/scala/coop/rchain/casper/helper/BlockGenerator.scala
  casper/src/test/scala/coop/rchain/casper/helper/BondingUtil.scala
  casper/src/test/scala/coop/rchain/casper/helper/RhoSpec.scala
  casper/src/test/scala/coop/rchain/casper/util/DeployValidationSpec.scala
  casper/src/test/scala/coop/rchain/casper/util/ProtoUtilTest.scala
  casper/src/test/scala/coop/rchain/casper/util/rholang/DeployIdTest.scala
  casper/src/test/scala/coop/rchain/casper/util/rholang/DeployerIdTest.scala
  casper/src/test/scala/coop/rchain/casper/util/rholang/InterpreterUtilTest.scala
  integration-tests/Pipfile
  integration-tests/Pipfile.lock
  integration-tests/test/http_client.py
  integration-tests/test/rnode.py
  integration-tests/test/test_slash.py
  integration-tests/test/test_web_api.py
  models/src/main/protobuf/CasperMessage.proto
  models/src/main/scala/coop/rchain/casper/protocol/CasperMessage.scala
  models/src/test/scala/coop/rchain/casper/protocol/DeployDataSpec.scala
  models/src/test/scala/coop/rchain/models/blockImplicits.scala
  node/src/main/scala/coop/rchain/node/Main.scala
  node/src/main/scala/coop/rchain/node/api/DeployGrpcServiceV1.scala
  node/src/main/scala/coop/rchain/node/api/WebApi.scala
  node/src/main/scala/coop/rchain/node/configuration/commandline/Options.scala
  node/src/main/scala/coop/rchain/node/configuration/model.scala
  node/src/main/scala/coop/rchain/node/revvaultexport/RhoTrieTraverser.scala
  node/src/main/scala/coop/rchain/node/web/Transaction.scala
  node/src/test/scala/coop/rchain/node/TransactionAPISpec.scala
  node/src/test/scala/coop/rchain/node/mergeablity/TreeHashMapMergeabilitySpec.scala
  node/src/test/scala/coop/rchain/node/revvaultexport/RhoTrieTraverserTest.scala
  rholang/src/test/scala/coop/rchain/rholang/StoragePrinterSpec.scala
Labels: Priority-High, need-hard-fork

#3638 Added configuration parameters for PoS contract
  casper/src/main/resources/PoS.rhox
  casper/src/main/scala/coop/rchain/casper/CasperConf.scala
  casper/src/main/scala/coop/rchain/casper/engine/ApproveBlockProtocol.scala
  casper/src/main/scala/coop/rchain/casper/engine/BlockApproverProtocol.scala
  casper/src/main/scala/coop/rchain/casper/engine/CasperLaunch.scala
  casper/src/main/scala/coop/rchain/casper/genesis/contracts/ProofOfStake.scala
  casper/src/test/scala/coop/rchain/casper/engine/BlockApproverProtocolTest.scala
  casper/src/test/scala/coop/rchain/casper/engine/Setup.scala
  casper/src/test/scala/coop/rchain/casper/genesis/GenesisTest.scala
  casper/src/test/scala/coop/rchain/casper/util/GenesisBuilder.scala
  node/src/main/resources/defaults.conf
  node/src/main/scala/coop/rchain/node/configuration/Configuration.scala
  node/src/test/scala/coop/rchain/node/configuration/commandline/ConfigMapperSpec.scala
  node/src/test/scala/coop/rchain/node/configuration/hocon/HoconConfigurationSpec.scala
Labels: enhancement, Priority-High

#3641 [RPC] Fix multi-sig vault with public key authentication
  casper/src/main/resources/MultiSigRevVault.rho
Labels: rpc-release
