Repository rchain/rchain, pull requests merged in 2022-08, with the labels that each got.

#3792 Add peek to NonNegativeNumber contract
  casper/src/main/resources/NonNegativeNumber.rho
  casper/src/test/resources/NonNegativeNumberTest.rho
Labels: rholang

#3794 Improve DAG visualizer for multi-parent finalizer with fringes in colors
  casper/src/main/scala/coop/rchain/casper/api/BlockApiImpl.scala
  casper/src/main/scala/coop/rchain/casper/api/GraphGenerator.scala
  graphz/src/main/scala/coop/rchain/graphz/Graphz.scala
Labels: enhancement

#3787 Refactor API tests using mocks
  casper/src/test/scala/coop/rchain/casper/api/BlockQueryResponseAPITest.scala
  casper/src/test/scala/coop/rchain/casper/api/BlocksResponseAPITest.scala
  casper/src/test/scala/coop/rchain/casper/api/BondedStatusAPITest.scala
  casper/src/test/scala/coop/rchain/casper/api/ExploratoryDeployAPITest.scala
  casper/src/test/scala/coop/rchain/casper/api/LastFinalizedAPITest.scala
  casper/src/test/scala/coop/rchain/casper/api/ListeningNameAPITest.scala
  casper/src/test/scala/coop/rchain/casper/api/MachineVerifiableDagSpec.scala
Labels: enhancement, build-tests-ci, blocking-others

#3795 Build node on Apple M1
  .gitignore
  build.sbt
  project/build.properties
  project/plugins.sbt
Labels: enhancement

#3797 Replace SyncVar in TransportLayerStub
  comm/src/test/scala/coop/rchain/p2p/EffectsTestInstances.scala
Labels: scala-2.13

#3790 Refactor DAG merger code
  block-storage/src/main/scala/coop/rchain/blockstorage/dag/DagMessageState.scala
  block-storage/src/main/scala/coop/rchain/blockstorage/dag/DagRepresentation.scala
  block-storage/src/main/scala/coop/rchain/blockstorage/dag/Finalizer.scala
  block-storage/src/main/scala/coop/rchain/blockstorage/dag/MessageMapSyntax.scala
  block-storage/src/main/scala/coop/rchain/blockstorage/package.scala
  casper/src/main/scala/coop/rchain/casper/MultiParentCasper.scala
  casper/src/main/scala/coop/rchain/casper/blocks/BlockDagStorageSyntax.scala
  casper/src/main/scala/coop/rchain/casper/dag/BlockDagKeyValueStorage.scala
  casper/src/main/scala/coop/rchain/casper/merging/BlockHashDagMerger.scala
  casper/src/main/scala/coop/rchain/casper/merging/BlockIndex.scala
  casper/src/main/scala/coop/rchain/casper/merging/MergeScope.scala
  casper/src/slowcooker/scala/coop.rchain.casper/MergingBenchmarkSpec.scala
  casper/src/test/scala/coop/rchain/casper/merging/MergeNumberChannelSpec.scala
  casper/src/test/scala/coop/rchain/casper/merging/MergingCases.scala
  node/src/test/scala/coop/rchain/node/mergeablity/ComputeMerge.scala
  sdk/src/main/scala/coop/rchain/sdk/dag/merging/ConflictResolutionLogic.scala
  sdk/src/test/scala/coop/rchain/sdk/merging/ConflictResolutionLogicSpec.scala
Labels: enhancement

#3801 Update lmdb-java version
  project/Dependencies.scala
Labels: enhancement

#3791 Attestations implementation
  block-storage/src/main/scala/coop/rchain/blockstorage/dag/MessageMapSyntax.scala
  casper/src/main/scala/coop/rchain/casper/MultiParentCasper.scala
  casper/src/main/scala/coop/rchain/casper/blocks/proposer/BlockCreator.scala
  casper/src/main/scala/coop/rchain/casper/blocks/proposer/Proposer.scala
  casper/src/main/scala/coop/rchain/casper/dag/BlockDagKeyValueStorage.scala
  casper/src/main/scala/coop/rchain/casper/merging/BlockIndex.scala
  casper/src/main/scala/coop/rchain/casper/merging/MergeScope.scala
  casper/src/test/scala/coop/rchain/casper/batch1/MultiParentCasperDeploySpec.scala
  casper/src/test/scala/coop/rchain/casper/helper/TestNode.scala
  node/src/main/scala/coop/rchain/node/runtime/Setup.scala
Labels: enhancement

#3806 Attestations refactoring
  block-storage/src/main/scala/coop/rchain/blockstorage/dag/Finalizer.scala
  casper/src/main/scala/coop/rchain/casper/blocks/proposer/BlockCreator.scala
  casper/src/main/scala/coop/rchain/casper/blocks/proposer/Proposer.scala
  casper/src/main/scala/coop/rchain/casper/dag/BlockDagKeyValueStorage.scala
  casper/src/test/scala/coop/rchain/casper/helper/TestNode.scala
  sdk/src/main/scala/coop/rchain/sdk/consensus/Stake.scala
Labels: Priority-Low, GoodToHave

#3809 Bugfix. Remove genesis from conflict set.
  casper/src/main/scala/coop/rchain/casper/merging/MergeScope.scala
Labels: bug-fix

#3803 Fix of sync issue when block is received but not added to DAG
  casper/src/main/scala/coop/rchain/casper/blocks/BlockReceiver.scala
  casper/src/main/scala/coop/rchain/casper/engine/NodeRunning.scala
  casper/src/test/scala/coop/rchain/casper/batch2/BlockReceiverEffectsSpec.scala
  node/src/main/scala/coop/rchain/node/runtime/Setup.scala
Labels: bug-fix
