Repository rchain/rchain, pull requests merged in 2022-07, with the labels that each got.

#3742 Abstract conflict resolution logic
  casper/src/main/scala/coop/rchain/casper/MultiParentCasper.scala
  casper/src/main/scala/coop/rchain/casper/merging/BlockHashDagMerger.scala
  casper/src/main/scala/coop/rchain/casper/merging/BlockIndex.scala
  casper/src/main/scala/coop/rchain/casper/merging/ConflictSetMerger.scala
  casper/src/main/scala/coop/rchain/casper/merging/DagMerger.scala
  casper/src/main/scala/coop/rchain/casper/merging/DeployChainIndex.scala
  casper/src/main/scala/coop/rchain/casper/merging/DeployIndex.scala
  casper/src/main/scala/coop/rchain/casper/rholang/InterpreterUtil.scala
  casper/src/slowcooker/scala/coop.rchain.casper/MergingBenchmarkSpec.scala
  casper/src/test/scala/coop/rchain/casper/merging/MergeNumberChannelSpec.scala
  casper/src/test/scala/coop/rchain/casper/merging/MergingCases.scala
  node/src/test/scala/coop/rchain/node/mergeablity/ComputeMerge.scala
  node/src/test/scala/coop/rchain/node/mergeablity/MergingBranchMergerSpec.scala
  rholang/src/main/scala/coop/rchain/rholang/interpreter/RhoHistoryRepositorySyntax.scala
  rholang/src/main/scala/coop/rchain/rholang/package.scala
  rspace/src/main/scala/coop/rchain/rspace/merger/EventLogMergingLogic.scala
  rspace/src/test/scala/coop/rchain/rspace/merging/EventsMergingLogicSpec.scala
  sdk/src/main/scala/coop/rchain/sdk/dag/merging/DagMergingLogic.scala
  sdk/src/main/scala/coop/rchain/sdk/primitive/MapSyntax.scala
  sdk/src/main/scala/coop/rchain/sdk/syntax/all.scala
  sdk/src/test/scala/coop/rchain/sdk/merging/DagMergingLogicSpec.scala
  shared/src/main/scala/coop/rchain/shared/package.scala
Labels: enhancement

#3718 Changed Web API data-at-name-by-block-hash to accept Par object
  integration-tests/test/http_client.py
  integration-tests/test/test_web_api.py
  node/src/main/scala/coop/rchain/node/api/WebApi.scala
  node/src/test/scala/coop/rchain/node/RhoExprToParSpec.scala
  rholang/src/main/scala/coop/rchain/rholang/interpreter/RhoType.scala
Labels: Priority-Low

#3761 Implement host check for peers to prevent loopback connections
  comm/src/main/scala/coop/rchain/comm/rp/HandleMessages.scala
  comm/src/test/scala/coop/rchain/comm/rp/HandleProtocolHandshakeSpec.scala
Labels: enhancement

#3728 Add BigInt support in Rholang
  models/src/main/protobuf/RhoTypes.proto
  models/src/main/scala/coop/rchain/models/BigIntTypeMapper.scala
  models/src/main/scala/coop/rchain/models/EqualsM.scala
  models/src/main/scala/coop/rchain/models/HashM.scala
  models/src/main/scala/coop/rchain/models/Pretty.scala
  models/src/main/scala/coop/rchain/models/rholang/implicits.scala
  models/src/main/scala/coop/rchain/models/rholang/sorter/ConnectiveSortMatcher.scala
  models/src/main/scala/coop/rchain/models/rholang/sorter/ExprSortMatcher.scala
  models/src/main/scala/coop/rchain/models/rholang/sorter/ScoreTree.scala
  models/src/test/scala/coop/rchain/models/EqualMSpec.scala
  models/src/test/scala/coop/rchain/models/HashMSpec.scala
  models/src/test/scala/coop/rchain/models/rholang/SortTest.scala
  rholang/src/main/bnfc/rholang_mercury.cf
  rholang/src/main/scala/coop/rchain/rholang/interpreter/PrettyPrinter.scala
  rholang/src/main/scala/coop/rchain/rholang/interpreter/Reduce.scala
  rholang/src/main/scala/coop/rchain/rholang/interpreter/Substitute.scala
  rholang/src/main/scala/coop/rchain/rholang/interpreter/accounting/Costs.scala
  rholang/src/main/scala/coop/rchain/rholang/interpreter/compiler/normalizer/GroundNormalizeMatcher.scala
  rholang/src/main/scala/coop/rchain/rholang/interpreter/compiler/normalizer/processes/PSimpleTypeNormalizer.scala
  rholang/src/main/scala/coop/rchain/rholang/interpreter/matcher/ParCount.scala
  rholang/src/main/scala/coop/rchain/rholang/interpreter/matcher/SpatialMatcher.scala
  rholang/src/test/scala/coop/rchain/rholang/interpreter/BigIntNormalizerSpec.scala
  rholang/src/test/scala/coop/rchain/rholang/interpreter/PrettyPrinterTest.scala
  rholang/src/test/scala/coop/rchain/rholang/interpreter/ReduceSpec.scala
  rholang/src/test/scala/coop/rchain/rholang/interpreter/SubstituteTest.scala
  rholang/src/test/scala/coop/rchain/rholang/interpreter/accounting/RholangMethodsCostsSpec.scala
  rholang/src/test/scala/coop/rchain/rholang/interpreter/compiler/normalizer/GroundMatcherSpec.scala
  rholang/src/test/scala/coop/rchain/rholang/interpreter/compiler/normalizer/ProcMatcherSpec.scala
  rholang/src/test/scala/coop/rchain/rholang/interpreter/matcher/MatchTest.scala
Labels: enhancement, rholang

#3772 Add release/** pattern to trigger CI workflow
  .github/workflows/continuous-integration.yml
Labels: build-tests-ci

#3765 Make mergeable overflow rejections discard the whole dependency tree
  casper/src/main/scala/coop/rchain/casper/merging/BlockIndex.scala
  casper/src/main/scala/coop/rchain/casper/merging/DeployChainIndex.scala
  casper/src/slowcooker/scala/coop.rchain.casper/MergingBenchmarkSpec.scala
  casper/src/test/scala/coop/rchain/casper/merging/MergeNumberChannelSpec.scala
  casper/src/test/scala/coop/rchain/casper/merging/MergingCases.scala
  sdk/src/main/scala/coop/rchain/sdk/dag/merging/DagMergingLogic.scala
  sdk/src/test/scala/coop/rchain/sdk/merging/DagMergingLogicSpec.scala
Labels: enhancement

#3741 Unit tests for BlockReceiver effects
  casper/src/test/scala/coop/rchain/casper/batch2/BlockReceiverEffectsSpec.scala
  project/CompilerSettings.scala
  project/Dependencies.scala
Labels: build-tests-ci

#3782 Move RhoType to models project
  casper/src/main/scala/coop/rchain/casper/api/BlockApiImpl.scala
  casper/src/main/scala/coop/rchain/casper/protocol/client/ListenAtName.scala
  casper/src/main/scala/coop/rchain/casper/rholang/BlockRandomSeed.scala
  casper/src/main/scala/coop/rchain/casper/rholang/syntax/RuntimeSyntax.scala
  casper/src/main/scala/coop/rchain/casper/rholang/sysdeploys/CheckBalance.scala
  casper/src/main/scala/coop/rchain/casper/rholang/sysdeploys/CloseBlockDeploy.scala
  casper/src/main/scala/coop/rchain/casper/rholang/sysdeploys/PreChargeDeploy.scala
  casper/src/main/scala/coop/rchain/casper/rholang/sysdeploys/RefundDeploy.scala
  casper/src/main/scala/coop/rchain/casper/rholang/sysdeploys/SlashDeploy.scala
  casper/src/main/scala/coop/rchain/casper/rholang/types/SystemDeploy.scala
  casper/src/test/scala/coop/rchain/casper/genesis/AuthKeyUpdateSpec.scala
  casper/src/test/scala/coop/rchain/casper/genesis/PosUpdateSpec.scala
  casper/src/test/scala/coop/rchain/casper/helper/BlockDataContract.scala
  casper/src/test/scala/coop/rchain/casper/helper/DeployerIdContract.scala
  casper/src/test/scala/coop/rchain/casper/helper/RhoLoggerContract.scala
  casper/src/test/scala/coop/rchain/casper/helper/Secp256k1SignContract.scala
  casper/src/test/scala/coop/rchain/casper/helper/SysAuthTokenContract.scala
  casper/src/test/scala/coop/rchain/casper/helper/TestResultCollector.scala
  casper/src/test/scala/coop/rchain/casper/merging/MergeNumberChannelSpec.scala
  casper/src/test/scala/coop/rchain/casper/rholang/Resources.scala
  models/src/main/scala/coop/rchain/models/rholang/RhoType.scala
  node/src/main/scala/coop/rchain/node/api/WebApi.scala
  node/src/main/scala/coop/rchain/node/revvaultexport/RhoTrieTraverser.scala
  node/src/main/scala/coop/rchain/node/revvaultexport/StateBalances.scala
  node/src/main/scala/coop/rchain/node/revvaultexport/mainnet1/StateBalanceMain.scala
  node/src/test/scala/coop/rchain/node/revvaultexport/RhoTrieTraverserTest.scala
  rholang/src/main/scala/coop/rchain/rholang/interpreter/Reduce.scala
  rholang/src/main/scala/coop/rchain/rholang/interpreter/SystemProcesses.scala
  rholang/src/main/scala/coop/rchain/rholang/interpreter/merging/RholangMergingLogic.scala
  rholang/src/test/scala/coop/rchain/rholang/interpreter/CostAccountingReducerTest.scala
  rholang/src/test/scala/coop/rchain/rholang/interpreter/CryptoChannelsSpec.scala
Labels: enhancement

#3783 Remove custom unsafeRunSync as duplicated from Task
  casper/src/slowcooker/scala/coop.rchain.casper/HashSetCasperSpecification.scala
  casper/src/test/scala/coop/rchain/casper/addblock/MultiParentCasperAddBlockSpec.scala
  casper/src/test/scala/coop/rchain/casper/util/GenesisBuilder.scala
  casper/src/test/scala/coop/rchain/casper/util/comm/CommUtilSpec.scala
  comm/src/test/scala/coop/rchain/comm/transport/StreamHandlerSpec.scala
  node/src/main/scala/coop/rchain/node/Main.scala
  rholang/src/main/scala/coop/rchain/rholang/interpreter/RholangCLI.scala
  rholang/src/test/scala/coop/rchain/rholang/interpreter/CryptoChannelsSpec.scala
  rholang/src/test/scala/coop/rchain/rholang/interpreter/PersistentStoreTester.scala
  rholang/src/test/scala/coop/rchain/rholang/interpreter/ReduceSpec.scala
  rholang/src/test/scala/coop/rchain/rholang/interpreter/accounting/RholangMethodsCostsSpec.scala
  rholang/src/test/scala/coop/rchain/rholang/interpreter/matcher/MatcherMonadSpec.scala
  rspace-bench/src/test/scala/coop/rchain/rspace/bench/BasicBench.scala
  rspace-bench/src/test/scala/coop/rchain/rspace/bench/EvalBenchStateBase.scala
  rspace-bench/src/test/scala/coop/rchain/rspace/bench/RhoBenchBaseState.scala
  rspace-bench/src/test/scala/coop/rchain/rspace/bench/RhoReplayBenchBaseState.scala
  rspace/src/test/scala/coop/rchain/rspace/ExportImportTests.scala
  rspace/src/test/scala/coop/rchain/rspace/ReplayRSpaceTests.scala
  rspace/src/test/scala/coop/rchain/rspace/StorageTestsBase.scala
  rspace/src/test/scala/coop/rchain/rspace/concurrent/TwoStepLockTest.scala
  shared/src/main/scala/coop/rchain/catscontrib/taskOps.scala
  shared/src/test/scala/coop/rchain/shared/scalatestcontrib.scala
Labels: build-tests-ci

#3789 Fix dependency computation bug
  casper/src/main/scala/coop/rchain/casper/merging/BlockHashDagMerger.scala
  casper/src/main/scala/coop/rchain/casper/merging/DeployChainIndex.scala
  casper/src/test/scala/coop/rchain/casper/merging/MergeNumberChannelSpec.scala
  casper/src/test/scala/coop/rchain/casper/rholang/InterpreterUtilTest.scala
  sdk/src/main/scala/coop/rchain/sdk/dag/merging/DagMergingLogic.scala
  sdk/src/test/scala/coop/rchain/sdk/merging/DagMergingLogicSpec.scala
Labels: bug-fix
