Repository rchain/rchain, pull requests merged in 2022-04, with the labels that each got.

#3649 Add short-circuit evaluation boolean syntax
  models/src/main/protobuf/RhoTypes.proto
  models/src/main/scala/coop/rchain/models/rholang/implicits.scala
  models/src/main/scala/coop/rchain/models/rholang/sorter/ExprSortMatcher.scala
  models/src/main/scala/coop/rchain/models/rholang/sorter/ScoreTree.scala
  node/src/main/scala/coop/rchain/node/encode/JsonEncoder.scala
  rholang/src/main/bnfc/rholang_mercury.cf
  rholang/src/main/scala/coop/rchain/rholang/interpreter/PrettyPrinter.scala
  rholang/src/main/scala/coop/rchain/rholang/interpreter/Reduce.scala
  rholang/src/main/scala/coop/rchain/rholang/interpreter/Substitute.scala
  rholang/src/main/scala/coop/rchain/rholang/interpreter/compiler/normalize.scala
  rholang/src/test/scala/coop/rchain/rholang/interpreter/ShortCircuitBooleanSpec.scala
Labels: rholang

#3652 [RPC] Add short circuit boolean evaluation
  models/src/main/protobuf/RhoTypes.proto
  models/src/main/scala/coop/rchain/models/rholang/implicits.scala
  models/src/main/scala/coop/rchain/models/rholang/sorter/ExprSortMatcher.scala
  models/src/main/scala/coop/rchain/models/rholang/sorter/ScoreTree.scala
  node/src/main/scala/coop/rchain/node/encode/JsonEncoder.scala
  rholang/src/main/bnfc/rholang_mercury.cf
  rholang/src/main/scala/coop/rchain/rholang/interpreter/PrettyPrinter.scala
  rholang/src/main/scala/coop/rchain/rholang/interpreter/Reduce.scala
  rholang/src/main/scala/coop/rchain/rholang/interpreter/Substitute.scala
  rholang/src/main/scala/coop/rchain/rholang/interpreter/compiler/normalize.scala
  rholang/src/test/scala/coop/rchain/rholang/interpreter/ShortCircuitBooleanSpec.scala
Labels: rholang

#3654 [RPC]Fix MultiSigVault boolean bug and add test cases
  casper/src/main/resources/MultiSigRevVault.rho
  casper/src/main/scala/coop/rchain/casper/util/ConstructDeploy.scala
  casper/src/test/resources/MultiSigRevVaultTest.rho
  casper/src/test/resources/MultiSigVault/posMultiSigConfirm.rho
  casper/src/test/resources/MultiSigVault/posMultiSigTransfer.rho
  casper/src/test/resources/MultiSigVault/transferToPOSMultiSig.rho
  casper/src/test/scala/coop/rchain/casper/genesis/POSMultiSigTransferSpec.scala
  models/src/main/scala/coop/rchain/models/ByteArraySyntax.scala
  rholang/src/main/scala/coop/rchain/rholang/build/CompiledRholangSource.scala
Labels: rpc-release

#3648 Fix MultiSigVault boolean bug and add test cases
  casper/src/main/resources/MultiSigRevVault.rho
  casper/src/main/scala/coop/rchain/casper/util/ConstructDeploy.scala
  casper/src/test/resources/MultiSigRevVaultTest.rho
  casper/src/test/resources/MultiSigVault/posMultiSigConfirm.rho
  casper/src/test/resources/MultiSigVault/posMultiSigTransfer.rho
  casper/src/test/resources/MultiSigVault/transferToPOSMultiSig.rho
  casper/src/test/scala/coop/rchain/casper/genesis/POSMultiSigTransferSpec.scala
  models/src/main/scala/coop/rchain/models/ByteArraySyntax.scala
  rholang/src/main/scala/coop/rchain/rholang/build/CompiledRholangSource.scala
Labels: bug-fix, rholang

#3658 Change LFS chunk size to 750 nodes
  casper/src/main/scala/coop/rchain/casper/engine/LfsTupleSpaceRequester.scala
Labels: feature-branch

#3653 [v0.12.x] Add transaction balance fix
  node/src/main/scala/coop/rchain/node/revvaultexport/mainnet1/reporting/MergeBalanceMain.scala
  node/src/main/scala/coop/rchain/node/revvaultexport/mainnet1/reporting/TransactionBalanceMain.scala
  node/src/main/scala/coop/rchain/node/revvaultexport/reporting/TransactionBalances.scala
Labels: bug-fix

#3661 Remove deprecated code (estimator, safety oracle)
  .github/workflows/continuous-integration.yml
  block-storage/src/main/scala/coop/rchain/blockstorage/dag/BlockDagKeyValueStorage.scala
  block-storage/src/main/scala/coop/rchain/blockstorage/dag/BlockDagStorage.scala
  casper/src/main/scala/coop/rchain/casper/Casper.scala
  casper/src/main/scala/coop/rchain/casper/MultiParentCasperImpl.scala
  casper/src/main/scala/coop/rchain/casper/SafetyOracle.scala
  casper/src/main/scala/coop/rchain/casper/Validate.scala
  casper/src/main/scala/coop/rchain/casper/api/BlockAPI.scala
  casper/src/main/scala/coop/rchain/casper/api/BlockReportAPI.scala
  casper/src/main/scala/coop/rchain/casper/blocks/proposer/Proposer.scala
  casper/src/main/scala/coop/rchain/casper/engine/CasperLaunch.scala
  casper/src/main/scala/coop/rchain/casper/engine/Engine.scala
  casper/src/main/scala/coop/rchain/casper/engine/GenesisCeremonyMaster.scala
  casper/src/main/scala/coop/rchain/casper/engine/GenesisValidator.scala
  casper/src/main/scala/coop/rchain/casper/engine/Initializing.scala
  casper/src/main/scala/coop/rchain/casper/finality/Finalizer.scala
  casper/src/main/scala/coop/rchain/casper/safety/CliqueOracle.scala
  casper/src/main/scala/coop/rchain/casper/util/ProtoUtil.scala
  casper/src/test/scala/coop/rchain/casper/addblock/MultiParentCasperAddBlockSpec.scala
  casper/src/test/scala/coop/rchain/casper/api/BlockQueryResponseAPITest.scala
  casper/src/test/scala/coop/rchain/casper/api/BlocksResponseAPITest.scala
  casper/src/test/scala/coop/rchain/casper/api/BondedStatusAPITest.scala
  casper/src/test/scala/coop/rchain/casper/api/ExploratoryDeployAPITest.scala
  casper/src/test/scala/coop/rchain/casper/api/LastFinalizedAPITest.scala
  casper/src/test/scala/coop/rchain/casper/api/ListeningNameAPITest.scala
  casper/src/test/scala/coop/rchain/casper/batch1/MultiParentCasperFinalizationSpec.scala
  casper/src/test/scala/coop/rchain/casper/batch2/CliqueOracleTest.scala
  casper/src/test/scala/coop/rchain/casper/batch2/EstimatorTest.scala
  casper/src/test/scala/coop/rchain/casper/batch2/FinalizerTest.scala
  casper/src/test/scala/coop/rchain/casper/batch2/LimitedParentDepthSpec.scala
  casper/src/test/scala/coop/rchain/casper/batch2/SingleParentCasperSpec.scala
  casper/src/test/scala/coop/rchain/casper/batch2/ValidateTest.scala
  casper/src/test/scala/coop/rchain/casper/engine/Setup.scala
  casper/src/test/scala/coop/rchain/casper/helper/TestNode.scala
  casper/src/test/scala/coop/rchain/casper/helper/UnlimitedParentsEstimatorFixture.scala
  casper/src/test/scala/coop/rchain/casper/util/rholang/Resources.scala
  integration-tests/test/test_slash.py
  models/src/main/protobuf/DeployServiceV1.proto
  node/src/main/scala/coop/rchain/node/api/DeployGrpcServiceV1.scala
  node/src/main/scala/coop/rchain/node/api/ProposeGrpcServiceV1.scala
  node/src/main/scala/coop/rchain/node/api/WebApi.scala
  node/src/main/scala/coop/rchain/node/runtime/APIServers.scala
  node/src/main/scala/coop/rchain/node/runtime/Setup.scala
Labels: feature-branch

#3634 Fix and re-enable block retriever spec
  .github/workflows/continuous-integration.yml
  casper/src/test/scala/coop/rchain/casper/sync/BlockRetrieverRequesAllSpec.scala
  casper/src/test/scala/coop/rchain/casper/sync/BlockRetrieverSpec.scala
Labels: build-tests-ci, bug-fix

#3664 Casper (equivocation) cleanup (BlockAPI/BlockReportAPI)
  block-storage/src/main/scala/coop/rchain/blockstorage/BlockStoreSyntax.scala
  block-storage/src/main/scala/coop/rchain/blockstorage/dag/BlockDagStorage.scala
  block-storage/src/main/scala/coop/rchain/blockstorage/dag/EquivocationTrackerStore.scala
  block-storage/src/main/scala/coop/rchain/blockstorage/dag/codecs.scala
  block-storage/src/main/scala/coop/rchain/blockstorage/deploy/KeyValueDeployStorage.scala
  block-storage/src/test/scala/coop/rchain/blockstorage/dag/IndexedBlockDagStorage.scala
  casper/src/main/scala/coop/rchain/casper/Casper.scala
  casper/src/main/scala/coop/rchain/casper/EquivocationDetector.scala
  casper/src/main/scala/coop/rchain/casper/MultiParentCasperImpl.scala
  casper/src/main/scala/coop/rchain/casper/api/BlockAPI.scala
  casper/src/main/scala/coop/rchain/casper/api/BlockReportAPI.scala
  casper/src/main/scala/coop/rchain/casper/blocks/BlockProcessor.scala
  casper/src/main/scala/coop/rchain/casper/dag/BlockDagKeyValueStorage.scala
  casper/src/main/scala/coop/rchain/casper/engine/CasperLaunch.scala
  casper/src/test/scala/coop/rchain/casper/addblock/MultiParentCasperAddBlockSpec.scala
  casper/src/test/scala/coop/rchain/casper/api/BlockQueryResponseAPITest.scala
  casper/src/test/scala/coop/rchain/casper/api/BlocksResponseAPITest.scala
  casper/src/test/scala/coop/rchain/casper/api/BondedStatusAPITest.scala
  casper/src/test/scala/coop/rchain/casper/api/LastFinalizedAPITest.scala
  casper/src/test/scala/coop/rchain/casper/api/ListeningNameAPITest.scala
  casper/src/test/scala/coop/rchain/casper/dag/BlockDagKeyValueStorageTest.scala
  casper/src/test/scala/coop/rchain/casper/engine/BlockApproverProtocolTest.scala
  casper/src/test/scala/coop/rchain/casper/engine/Setup.scala
  casper/src/test/scala/coop/rchain/casper/helper/BlockDagStorageFixture.scala
  casper/src/test/scala/coop/rchain/casper/helper/TestNode.scala
  casper/src/test/scala/coop/rchain/casper/util/GenesisBuilder.scala
  models/src/main/scala/coop/rchain/models/EquivocationRecord.scala
  node/src/main/scala/coop/rchain/node/api/DeployGrpcServiceV1.scala
  node/src/main/scala/coop/rchain/node/api/WebApi.scala
  node/src/main/scala/coop/rchain/node/revvaultexport/reporting/TransactionBalances.scala
  node/src/main/scala/coop/rchain/node/runtime/APIServers.scala
  node/src/main/scala/coop/rchain/node/runtime/Setup.scala
  node/src/test/scala/coop/rchain/node/TransactionAPISpec.scala
  node/src/test/scala/coop/rchain/node/mergeablity/ComputeMerge.scala
  node/src/test/scala/coop/rchain/node/mergeablity/MergingBranchMergerSpec.scala
Labels: enhancement

#3662 Refactor BlockAPI
  casper/src/main/scala/coop/rchain/casper/api/BlockAPIImpl.scala
  casper/src/main/scala/coop/rchain/casper/api/BlockAPI_v2.scala
Labels: enhancement
