Repository rchain/rchain, pull requests merged in 2022-06, with the labels that each got.

#3696 Added class KeySegment, replace KeyPath to KeySegment in code
  node/src/test/scala/coop/rchain/node/perf/HistoryGenKeySpec.scala
  rspace/src/main/scala/coop/rchain/rspace/history/History.scala
  rspace/src/main/scala/coop/rchain/rspace/history/HistoryAction.scala
  rspace/src/main/scala/coop/rchain/rspace/history/HistoryMergingInstances.scala
  rspace/src/main/scala/coop/rchain/rspace/history/HistoryRepositoryImpl.scala
  rspace/src/main/scala/coop/rchain/rspace/history/HistoryStore.scala
  rspace/src/main/scala/coop/rchain/rspace/history/KeySegment.scala
  rspace/src/main/scala/coop/rchain/rspace/history/RadixTree.scala
  rspace/src/main/scala/coop/rchain/rspace/history/instances/RSpaceHistoryReaderImpl.scala
  rspace/src/main/scala/coop/rchain/rspace/history/instances/RadixHistory.scala
  rspace/src/main/scala/coop/rchain/rspace/serializers/ScodecSerialize.scala
  rspace/src/main/scala/coop/rchain/rspace/state/RSpaceExporter.scala
  rspace/src/test/scala/coop/rchain/rspace/history/HistoryActionTests.scala
  rspace/src/test/scala/coop/rchain/rspace/history/HistoryRepositorySpec.scala
  rspace/src/test/scala/coop/rchain/rspace/history/InMemoryHistoryTestBase.scala
  rspace/src/test/scala/coop/rchain/rspace/history/RadixTreeSpec.scala
Labels: GoodToHave, radix-history

#3695 Binding of BlockAPI deployStatus to gRPC, WebAPI and CLI
  block-storage/src/main/scala/coop/rchain/blockstorage/dag/BlockDagStorage.scala
  casper/src/main/scala/coop/rchain/casper/BlockExecutionTracker.scala
  casper/src/main/scala/coop/rchain/casper/api/BlockApi.scala
  casper/src/main/scala/coop/rchain/casper/api/BlockApiImpl.scala
  casper/src/main/scala/coop/rchain/casper/dag/BlockDagKeyValueStorage.scala
  casper/src/main/scala/coop/rchain/casper/protocol/client/DeployRuntime.scala
  casper/src/main/scala/coop/rchain/casper/protocol/client/DeployService.scala
  casper/src/main/scala/coop/rchain/casper/rholang/RuntimeManager.scala
  casper/src/test/scala/coop/rchain/casper/helper/BlockApiFixture.scala
  casper/src/test/scala/coop/rchain/casper/helper/TestNode.scala
  models/src/main/protobuf/DeployServiceV1.proto
  node/src/main/scala/coop/rchain/node/Main.scala
  node/src/main/scala/coop/rchain/node/api/DeployGrpcServiceV1.scala
  node/src/main/scala/coop/rchain/node/api/WebApi.scala
  node/src/main/scala/coop/rchain/node/api/json/JsonSchemaDerivation.scala
  node/src/main/scala/coop/rchain/node/api/v1/WebApiEndpoints.scala
  node/src/main/scala/coop/rchain/node/configuration/commandline/Options.scala
  node/src/main/scala/coop/rchain/node/configuration/model.scala
  node/src/main/scala/coop/rchain/node/runtime/Setup.scala
  node/src/main/scala/coop/rchain/node/web/WebApiDocsV1.scala
  node/src/main/scala/coop/rchain/node/web/WebApiRoutes.scala
  node/src/main/scala/coop/rchain/node/web/WebApiRoutesV1.scala
  rholang/src/main/scala/coop/rchain/rholang/interpreter/RhoType.scala
  sdk/src/main/scala/coop/rchain/sdk/primitive/ThrowableSyntax.scala
  sdk/src/main/scala/coop/rchain/sdk/syntax/all.scala
  sdk/src/main/scala/coop/rchain/sdk/syntax/package.scala
Labels: enhancement, API

#3727 Effectful unit-testing with Monix Testing and ScalaTest
  casper/src/test/scala/coop/rchain/casper/rholang/RuntimeSpec.scala
  project/Dependencies.scala
Labels: enhancement, build-tests-ci, epic

#3703 Add pos-vault-pub-key parameter in genesis config
  casper/src/main/resources/Pos.rhox
  casper/src/main/scala/coop/rchain/casper/CasperConf.scala
  casper/src/main/scala/coop/rchain/casper/engine/NodeLaunch.scala
  casper/src/main/scala/coop/rchain/casper/genesis/contracts/ProofOfStake.scala
  casper/src/test/scala/coop/rchain/casper/genesis/GenesisTest.scala
  casper/src/test/scala/coop/rchain/casper/genesis/PosMultiSigTransferSpec.scala
  casper/src/test/scala/coop/rchain/casper/util/GenesisBuilder.scala
  integration-tests/resources/wallets/transfer_from_pos_vault.rho
  integration-tests/test/rnode.py
  integration-tests/test/test_wallets.py
  node/src/main/resources/defaults.conf
  node/src/main/scala/coop/rchain/node/configuration/commandline/ConfigMapper.scala
  node/src/main/scala/coop/rchain/node/configuration/commandline/Options.scala
  node/src/test/scala/coop/rchain/node/configuration/commandline/ConfigMapperSpec.scala
  node/src/test/scala/coop/rchain/node/configuration/hocon/HoconConfigurationSpec.scala
Labels: next-release

#3731 Removing unused unforgeable name predicting tools and api (1st part)
  casper/src/main/scala/coop/rchain/casper/rholang/RegistrySigGen.scala
  casper/src/test/scala/coop/rchain/casper/addblock/MultiParentCasperAddBlockSpec.scala
  casper/src/test/scala/coop/rchain/casper/batch1/MultiParentCasperRholangSpec.scala
  casper/src/test/scala/coop/rchain/casper/batch2/RholangBuildTest.scala
Labels: enhancement

#3722 Block receiver
  block-storage/src/main/scala/coop/rchain/blockstorage/casperbuffer/CasperBufferKeyValueStorage.scala
  block-storage/src/main/scala/coop/rchain/blockstorage/casperbuffer/CasperBufferStorage.scala
  block-storage/src/main/scala/coop/rchain/blockstorage/util/DoublyLinkedDagOperations.scala
  block-storage/src/test/scala/coop/rchain/blockstorage/casperbuffer/CasperBufferStorageTest.scala
  casper/src/main/scala/coop/rchain/casper/BlockStatus.scala
  casper/src/main/scala/coop/rchain/casper/MultiParentCasper.scala
  casper/src/main/scala/coop/rchain/casper/blocks/BlockProcessor.scala
  casper/src/main/scala/coop/rchain/casper/blocks/BlockReceiver.scala
  casper/src/main/scala/coop/rchain/casper/blocks/proposer/Proposer.scala
  casper/src/main/scala/coop/rchain/casper/engine/LfsBlockRequester.scala
  casper/src/main/scala/coop/rchain/casper/engine/NodeLaunch.scala
  casper/src/main/scala/coop/rchain/casper/engine/NodeRunning.scala
  casper/src/main/scala/coop/rchain/casper/engine/NodeSyncing.scala
  casper/src/test/scala/coop/rchain/casper/addblock/MultiParentCasperAddBlockSpec.scala
  casper/src/test/scala/coop/rchain/casper/batch1/MultiParentCasperCommunicationSpec.scala
  casper/src/test/scala/coop/rchain/casper/engine/LfsBlockRequesterEffectsSpec.scala
  casper/src/test/scala/coop/rchain/casper/engine/Setup.scala
  casper/src/test/scala/coop/rchain/casper/helper/TestNode.scala
  node/src/main/scala/coop/rchain/node/instances/BlockProcessorInstance.scala
  node/src/main/scala/coop/rchain/node/runtime/NodeRuntime.scala
  node/src/main/scala/coop/rchain/node/runtime/Setup.scala
  node/src/test/scala/coop/rchain/node/TransactionAPISpec.scala
  shared/src/main/scala/coop/rchain/fs2/Fs2StreamSyntax.scala
Labels: enhancement

#3729 Added unit - tests for BlockRandomSeed case class
  casper/src/main/scala/coop/rchain/casper/BlockRandomSeed.scala
  casper/src/test/scala/coop/rchain/casper/BlockRandomSeedSpec.scala
  rholang/src/main/scala/coop/rchain/rholang/interpreter/merging/RholangMergingLogic.scala
  rspace/src/main/scala/coop/rchain/rspace/hashing/Blake2b256Hash.scala
  rspace/src/main/scala/coop/rchain/rspace/history/ColdStore.scala
  rspace/src/test/scala/coop/rchain/rspace/history/HistoryRepositorySpec.scala
Labels: enhancement, blocking-others

#3734 Removed parameter allowPrivateAddresses and host check when node starts
  README.md
  comm/src/main/scala/coop/rchain/comm/discovery/GrpcKademliaRPC.scala
  comm/src/main/scala/coop/rchain/comm/package.scala
  comm/src/test/scala/coop/rchain/comm/discovery/GrpcKademliaRPCSpec.scala
  comm/src/test/scala/coop/rchain/comm/discovery/KademliaRPCSpec.scala
  integration-tests/test/rnode.py
  node/src/main/resources/defaults.conf
  node/src/main/scala/coop/rchain/node/Main.scala
  node/src/main/scala/coop/rchain/node/configuration/commandline/ConfigMapper.scala
  node/src/main/scala/coop/rchain/node/configuration/model.scala
  node/src/main/scala/coop/rchain/node/effects/package.scala
  node/src/main/scala/coop/rchain/node/runtime/NodeRuntime.scala
  node/src/test/scala/coop/rchain/node/configuration/commandline/ConfigMapperSpec.scala
  node/src/test/scala/coop/rchain/node/configuration/hocon/HoconConfigurationSpec.scala
Labels: enhancement

#3750 Make conflict resolution logic pure
  casper/src/main/scala/coop/rchain/casper/merging/ConflictSetMerger.scala
  casper/src/main/scala/coop/rchain/casper/merging/DagMerger.scala
  casper/src/test/scala/coop/rchain/casper/merging/MergeNumberChannelSpec.scala
Labels: enhancement

#3738 Unit-tests for BlockReceiverState
  casper/src/main/scala/coop/rchain/casper/blocks/BlockReceiver.scala
  casper/src/test/scala/coop/rchain/casper/batch2/BlockReceiverStateSpec.scala
Labels: build-tests-ci

#3754 Added check that shard name contains only ASCII characters
  casper/src/main/scala/coop/rchain/casper/BlockRandomSeed.scala
  casper/src/main/scala/coop/rchain/casper/Validate.scala
  models/src/main/scala/coop/rchain/models/StringSyntax.scala
  node/src/main/scala/coop/rchain/node/Main.scala
Labels: enhancement
