Repository rchain/rchain, pull requests merged in 2022-05, with the labels that each got.

#3637 Radix history unit tests
  rspace/src/main/scala/coop/rchain/rspace/history/RadixTree.scala
  rspace/src/main/scala/coop/rchain/rspace/history/instances/RadixHistory.scala
  rspace/src/test/scala/coop/rchain/rspace/history/RadixTreeSpec.scala
Labels: build-tests-ci, documentation, radix-history

#3687 Remove signature in insertSigned
  casper/src/main/resources/AuthKey.rho
  casper/src/main/resources/Either.rho
  casper/src/main/resources/ListOps.rho
  casper/src/main/resources/MakeMint.rho
  casper/src/main/resources/MultiSigRevVault.rho
  casper/src/main/resources/NonNegativeNumber.rho
  casper/src/main/resources/PoS.rhox
  casper/src/main/resources/Registry.rho
  casper/src/main/resources/RevVault.rho
  casper/src/test/resources/RegistryTest.rho
  casper/src/test/resources/RhoSpecContract.rho
  node/src/main/scala/coop/rchain/node/revvaultexport/mainnet1/StateBalanceMain.scala
Labels: enhancement

#3686 Changed type of fields value/ptr in classes Leaf and NodePtr, adaptation of code
  node/src/test/scala/coop/rchain/node/perf/HistoryGenKeySpec.scala
  rspace/src/main/scala/coop/rchain/rspace/history/History.scala
  rspace/src/main/scala/coop/rchain/rspace/history/RadixTree.scala
  rspace/src/main/scala/coop/rchain/rspace/history/instances/RSpaceHistoryReaderImpl.scala
  rspace/src/main/scala/coop/rchain/rspace/history/instances/RadixHistory.scala
  rspace/src/main/scala/coop/rchain/rspace/state/RSpaceExporter.scala
  rspace/src/main/scala/coop/rchain/rspace/state/RSpaceImporter.scala
  rspace/src/test/scala/coop/rchain/rspace/history/HistoryActionTests.scala
  rspace/src/test/scala/coop/rchain/rspace/history/RadixTreeSpec.scala
Labels: GoodToHave, radix-history

#3693 Block message version 2 (hash & validation)
  .github/workflows/continuous-integration.yml
  casper/src/main/scala/coop/rchain/casper/BlockStatus.scala
  casper/src/main/scala/coop/rchain/casper/Validate.scala
  casper/src/main/scala/coop/rchain/casper/blocks/BlockProcessor.scala
  casper/src/main/scala/coop/rchain/casper/engine/Initializing.scala
  casper/src/main/scala/coop/rchain/casper/genesis/Genesis.scala
  casper/src/main/scala/coop/rchain/casper/util/ProtoUtil.scala
  casper/src/test/scala/coop/rchain/casper/addblock/MultiParentCasperAddBlockSpec.scala
  casper/src/test/scala/coop/rchain/casper/batch2/ValidateTest.scala
  casper/src/test/scala/coop/rchain/casper/util/BlockHashSignatureSpec.scala
  integration-tests/test/test_slash.py
  models/src/main/scala/coop/rchain/models/BlockVersion.scala
  models/src/test/scala/coop/rchain/models/blockImplicits.scala
  node/src/main/scala/coop/rchain/node/instances/BlockProcessorInstance.scala
Labels: bug-fix

#3704 Fix switch to block version 2
  casper/src/main/scala/coop/rchain/casper/engine/CasperLaunch.scala
  casper/src/test/scala/coop/rchain/casper/helper/TestNode.scala
Labels: bug-fix

#3705 Included latest block number is status API
  casper/src/main/scala/coop/rchain/casper/api/BlockApiImpl.scala
  models/src/main/protobuf/DeployServiceCommon.proto
  node/src/main/scala/coop/rchain/node/api/WebApi.scala
Labels: enhancement, API

#3682 Find deploy method
  casper/src/main/scala/coop/rchain/casper/dag/BlockDagKeyValueStorage.scala
  casper/src/main/scala/coop/rchain/casper/rholang/RuntimeDeployResult.scala
  casper/src/main/scala/coop/rchain/casper/rholang/RuntimeManager.scala
  casper/src/main/scala/coop/rchain/casper/rholang/syntax/RuntimeReplaySyntax.scala
  casper/src/main/scala/coop/rchain/casper/rholang/syntax/RuntimeSyntax.scala
  casper/src/test/scala/coop/rchain/casper/batch2/ValidateTest.scala
  casper/src/test/scala/coop/rchain/casper/engine/Setup.scala
  casper/src/test/scala/coop/rchain/casper/genesis/GenesisTest.scala
  casper/src/test/scala/coop/rchain/casper/helper/TestNode.scala
  casper/src/test/scala/coop/rchain/casper/rholang/Resources.scala
  casper/src/test/scala/coop/rchain/casper/rholang/RuntimeManagerTest.scala
  casper/src/test/scala/coop/rchain/casper/util/GenesisBuilder.scala
  node/src/main/scala/coop/rchain/node/runtime/Setup.scala
  node/src/test/scala/coop/rchain/node/mergeablity/ComputeMerge.scala
Labels: API

#3709 [RPC] Sync feature/v0.12-rpc with feature/v0.12 (included block hash fix)
  .github/workflows/continuous-integration.yml
  casper/src/main/scala/coop/rchain/casper/BlockStatus.scala
  casper/src/main/scala/coop/rchain/casper/Validate.scala
  casper/src/main/scala/coop/rchain/casper/blocks/BlockProcessor.scala
  casper/src/main/scala/coop/rchain/casper/engine/CasperLaunch.scala
  casper/src/main/scala/coop/rchain/casper/engine/Initializing.scala
  casper/src/main/scala/coop/rchain/casper/genesis/Genesis.scala
  casper/src/main/scala/coop/rchain/casper/util/ProtoUtil.scala
  casper/src/test/scala/coop/rchain/casper/addblock/MultiParentCasperAddBlockSpec.scala
  casper/src/test/scala/coop/rchain/casper/batch2/ValidateTest.scala
  casper/src/test/scala/coop/rchain/casper/helper/TestNode.scala
  casper/src/test/scala/coop/rchain/casper/util/BlockHashSignatureSpec.scala
  integration-tests/test/test_slash.py
  models/src/main/scala/coop/rchain/models/BlockVersion.scala
  models/src/test/scala/coop/rchain/models/blockImplicits.scala
  node/src/main/scala/coop/rchain/node/instances/BlockProcessorInstance.scala
  node/src/main/scala/coop/rchain/node/revvaultexport/mainnet1/reporting/MergeBalanceMain.scala
  node/src/main/scala/coop/rchain/node/revvaultexport/mainnet1/reporting/TransactionBalanceMain.scala
  node/src/main/scala/coop/rchain/node/revvaultexport/reporting/TransactionBalances.scala
Labels: rpc-release

#3706 Removed `prepare-deploy` API method and related code
  casper/src/main/scala/coop/rchain/casper/api/BlockApi.scala
  casper/src/main/scala/coop/rchain/casper/api/BlockApiImpl.scala
  docs/rnode-api/index.md
  integration-tests/test/http_client.py
  integration-tests/test/test_web_api.py
  models/src/main/protobuf/DeployServiceCommon.proto
  models/src/main/protobuf/DeployServiceV1.proto
  models/src/main/scala/coop/rchain/models/EqualsM.scala
  models/src/main/scala/coop/rchain/models/HashM.scala
  node/src/main/scala/coop/rchain/node/api/DeployGrpcServiceV1.scala
  node/src/main/scala/coop/rchain/node/api/WebApi.scala
  node/src/main/scala/coop/rchain/node/web/WebApiRoutes.scala
Labels: enhancement

#3485 System contract updates
  casper/src/main/resources/AuthKey.rho
  casper/src/main/resources/Either.rho
  casper/src/main/resources/ListOps.rho
  casper/src/main/resources/MakeMint.rho
  casper/src/main/resources/MultiSigRevVault.rho
  casper/src/main/resources/NonNegativeNumber.rho
  casper/src/main/resources/PoS.rhox
  casper/src/main/resources/Pos.rhox
  casper/src/main/resources/Registry.rho
  casper/src/main/resources/RevVault.rho
  casper/src/main/scala/coop/rchain/casper/genesis/contracts/ProofOfStake.scala
  casper/src/main/scala/coop/rchain/casper/rholang/syntax/RuntimeSyntax.scala
  casper/src/main/scala/coop/rchain/casper/rholang/sysdeploys/CloseBlockDeploy.scala
  casper/src/main/scala/coop/rchain/casper/rholang/sysdeploys/PreChargeDeploy.scala
  casper/src/main/scala/coop/rchain/casper/rholang/sysdeploys/RefundDeploy.scala
  casper/src/main/scala/coop/rchain/casper/rholang/sysdeploys/SlashDeploy.scala
  casper/src/test/resources/MakeMintTest.rho
  casper/src/test/resources/MultiSigVault/PosMultiSigConfirm.rho
  casper/src/test/resources/MultiSigVault/PosMultiSigTransfer.rho
  casper/src/test/resources/MultiSigVault/TransferToPosMultiSig.rho
  casper/src/test/resources/PosTest.rho
  casper/src/test/resources/RevVaultTest.rho
  casper/src/test/resources/TreeHashMapTest.rho
  casper/src/test/resources/UpdateAuthKey/UpdateAuthKey.rho
  casper/src/test/resources/UpdatePos/UpdatePos.rho
  casper/src/test/resources/UpdateRegistry/UpdateRegistry.rho
  casper/src/test/scala/coop/rchain/casper/genesis/AuthKeyUpdateSpec.scala
  casper/src/test/scala/coop/rchain/casper/genesis/PosMultiSigTransferSpec.scala
  casper/src/test/scala/coop/rchain/casper/genesis/PosUpdateSpec.scala
  casper/src/test/scala/coop/rchain/casper/genesis/RegistryUpdateSpec.scala
  casper/src/test/scala/coop/rchain/casper/genesis/contracts/PoSSpec.scala
  casper/src/test/scala/coop/rchain/casper/helper/BondingUtil.scala
  casper/src/test/scala/coop/rchain/casper/helper/TestNode.scala
  casper/src/test/scala/coop/rchain/casper/util/GenesisBuilder.scala
  node/src/main/scala/coop/rchain/node/revvaultexport/RhoTrieTraverser.scala
  node/src/main/scala/coop/rchain/node/revvaultexport/StateBalances.scala
  node/src/main/scala/coop/rchain/node/revvaultexport/mainnet1/StateBalanceMain.scala
  node/src/main/scala/coop/rchain/node/revvaultexport/reporting/TransactionBalances.scala
  node/src/main/scala/coop/rchain/node/web/Transaction.scala
  node/src/test/scala/coop/rchain/node/mergeablity/TreeHashMapMergeabilitySpec.scala
  node/src/test/scala/coop/rchain/node/revvaultexport/RhoTrieTraverserTest.scala
  node/src/test/scala/coop/rchain/node/revvaultexport/VaultBalanceGetterTest.scala
  rholang/src/main/scala/coop/rchain/rholang/build/CompiledRholangSource.scala
Labels: enhancement, blocking-others, need-hard-fork, rholang

#3711 Introduce new random seed for rholang deploy(part 1)
  rholang/src/main/scala/BlockRandomSeed.scala
Labels: enhancement
